services:
  portfolio:
    container_name: ${APPS_PLATFORM_PORTFOLIO_NAME}
    image: ${REGISTRY}/${APPS_PLATFORM_PORTFOLIO_IMAGE_NAME}:${APPS_PLATFORM_PORTFOLIO_VERSION}
    build:
      context: ../../../../apps/web/site
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY}
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          wget -qO- http://localhost:${APPS_PLATFORM_PORTFOLIO_DEFAULT_PORT}${APPS_PLATFORM_PORTFOLIO_HEALTH_PATH}
          || exit 1
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
