services:
  nginx-errors:
    image: ${EDGE_NGINX_IMAGE}
    container_name: ${EDGE_NGINX_NAME}
    restart: ${RESTART_POLICY}
    expose:
      - "${EDGE_NGINX_PORT}"
    volumes:
      - ../../../../edge/nginx/configs/nginx.${ENVIRONMENT}.conf:/etc/nginx/nginx.conf:ro
      - ../../../../edge/nginx/assets/errors:/usr/share/nginx/html/errors:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost${EDGE_NGINX_HEALTH_PATH} || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
