---
headscale_image: ""
headscale_domain: ""
headscale_listen_port: 8080
headscale_stun_port: 3478
headscale_remote_dir: "/opt/headscale"
headscale_config_dir: "{{ headscale_remote_dir }}/config"

vps_public_ip: ""
docker_network: "kubelab"
restart_policy: "unless-stopped"

# Tailscale CIDR for IP allocation
tailscale_cidr: "100.64.0.0/10"

# DNS config for Headscale's split DNS
headscale_dns_split: {}
headscale_dns_extra_records: []

# DERP relay
headscale_derp_enabled: true
headscale_derp_region_id: 999
headscale_derp_region_code: "kubelab"
headscale_derp_region_name: "KubeLab Homelab"
headscale_derp_verify_clients: true

# Database
headscale_db_type: "sqlite"
