services:
  web:
    image: "${REGISTRY}/${IMAGE_NAME}:${TAG}"
    container_name: ${CONTAINER_NAME}
    restart: always
    expose:
      - ${PORT}  
    env_file:
      - ./.env.prod
    networks:
      - proxy

networks:
  proxy:
    external: true
