repos:
  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validate message format
        entry: .github/hooks/validate-commit-msg.sh
        language: script
        stages: [commit-msg]
      - id: generate-env-example-files
        name: Generate environment files with placeholders
        entry: scripts/generate-env-example.sh
        language: script
        stages: [pre-commit]