services:
  blog:
    image: "${REGISTRY-docker.io/mlorentedev}/blog:${TAG:-latest}"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog
    restart: always
    expose:
      - ${PORT}  
    env_file:
      - ./.env
    volumes:
      - ./jekyll-site:/srv/jekyll
    networks:
      - proxy
      
networks:
  proxy:
    external: true
