services:
  blog:
    image: "${REGISTRY}/${IMAGE_NAME}:${TAG}"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    expose:
      - ${PORT}  
    env_file:
      - ./.env.dev
    volumes:
      - ./jekyll-site:/srv/jekyll
    networks:
      - proxy
      
networks:
  proxy:
    external: true
