services:
  blog:
    container_name: ${APPS_PLATFORM_BLOG_NAME}
    image: ${REGISTRY}/${APPS_PLATFORM_BLOG_IMAGE_NAME}:${APPS_PLATFORM_BLOG_VERSION}
    build:
      context: ../../../../apps/blog
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY}
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl -f http://localhost:${APPS_PLATFORM_BLOG_DEFAULT_PORT}${APPS_PLATFORM_BLOG_HEALTH_PATH}
          || exit 1
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    expose:
      - "${APPS_PLATFORM_BLOG_DEFAULT_PORT}"

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
