services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - ./.env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - proxy

  git_sync:
    image: registry.k8s.io/git-sync/git-sync:v4.2.3
    container_name: git_sync
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - vault:/git
    networks:
      - proxy

volumes:
  n8n_data:
  vault:

networks:
  proxy:
    external: true