"""Tests for TOOL-023: track the Argo CD hub SOPS keys in SECRET_CATALOG.

`make deploy-argocd` reads four hub credentials straight from `common.enc.yaml`
(Makefile ~413-416) — the Argo CD admin bcrypt hash, the Authelia→Argo CD OIDC
client secret, and the Slack / GitHub webhook secrets. `credentials generate`
writes two more hub secrets to the same file: the admin password (plaintext) and
the OIDC client-secret Argon2 hash. None were registered in `SECRET_CATALOG`, so
`toolkit secrets audit` never checked them: a hub with a blank OIDC secret still
reported "all present" (docs audit finding D64).

These tests pin:

1. All six hub key paths are registered in the catalog.
2. They are NOT machine-generable kinds — `secrets init` must never write these
   per-env (they live in common.enc.yaml, generated by `credentials generate` or
   supplied by the operator). Guards against a future kind change reintroducing
   per-env drift.
3. `audit()` now tracks them: present when the vault holds real values, and
   flagged missing when a hub key is absent (they are no longer invisible).
"""

from __future__ import annotations

from unittest.mock import patch

from toolkit.config.settings import PROJECT_ROOT
from toolkit.features.configuration import ConfigurationManager
from toolkit.features.secrets_manager import (
    SECRET_CATALOG,
    SecretKind,
    SecretsManager,
)

# Every argocd/hub key now tracked in common.enc.yaml. The first four are read by
# `deploy-argocd` (Makefile:413-416); admin_password + the OIDC hash are the
# sibling secrets `credentials generate` also writes.
ARGOCD_HUB_KEYS = (
    "argocd.admin_password",
    "argocd.admin_password_hash",
    "apps.services.security.authelia.oidc_client_secret_argocd",
    "apps.services.security.authelia.oidc_client_secret_argocd_hash",
    "argocd.slack_webhook_url",
    "argocd.github_webhook_secret",
)

# Kinds that `init_machine_secrets` auto-generates into the PER-ENV vault.
AUTO_KINDS = {
    SecretKind.RANDOM_HEX,
    SecretKind.RANDOM_TOKEN,
    SecretKind.OIDC_CLIENT_SECRET,
    SecretKind.RSA_KEY,
}

_CATALOG_BY_KEY = {s.key_path: s for s in SECRET_CATALOG}


class TestArgocdHubKeysRegistered:
    def test_all_four_hub_keys_are_in_catalog(self) -> None:
        registered = set(_CATALOG_BY_KEY)
        missing = [k for k in ARGOCD_HUB_KEYS if k not in registered]
        assert not missing, f"Argo CD hub keys absent from SECRET_CATALOG: {missing}"

    def test_hub_keys_are_not_machine_generable(self) -> None:
        # These live in common.enc.yaml; `secrets init` (per-env) must never write
        # them. Pin the invariant so a later kind change can't reintroduce drift.
        for key in ARGOCD_HUB_KEYS:
            spec = _CATALOG_BY_KEY[key]
            assert spec.kind not in AUTO_KINDS, f"{key} ({spec.kind}) would be auto-generated per-env"

    def test_hub_keys_audited_under_prod(self) -> None:
        # Hub = always-on management plane; audited under prod (see comment in catalog).
        for key in ARGOCD_HUB_KEYS:
            assert "prod" in _CATALOG_BY_KEY[key].envs, f"{key} must be audited in prod"


class TestAuditTracksArgocdHubKeys:
    _REAL = {
        "argocd": {
            "admin_password": "s3cr3t-pw",
            "admin_password_hash": "$2y$10$abcdefghijklmnopqrstuv",
            "slack_webhook_url": "https://hooks.slack.com/services/T00/B00/xxxxxxxx",
            "github_webhook_secret": "a-real-webhook-shared-secret",
        },
        "apps": {
            "services": {
                "security": {
                    "authelia": {
                        "oidc_client_secret_argocd": "a-real-oidc-token",
                        "oidc_client_secret_argocd_hash": "$argon2id$v=19$m=65536,t=3,p=4$realhash",
                    }
                }
            }
        },
    }

    def test_present_when_vault_holds_real_values(self) -> None:
        with patch.object(ConfigurationManager, "_decrypt_sops", return_value=self._REAL):
            result = SecretsManager(PROJECT_ROOT).audit("prod")
        for key in ARGOCD_HUB_KEYS:
            assert key in result.present, f"{key} should be tracked present"

    def test_missing_hub_key_is_flagged_not_invisible(self) -> None:
        # Drop the OIDC secret — the exact D64 scenario (blank hub OIDC reported clean).
        partial = {
            "argocd": self._REAL["argocd"],
            "apps": {"services": {"security": {"authelia": {}}}},
        }
        with patch.object(ConfigurationManager, "_decrypt_sops", return_value=partial):
            result = SecretsManager(PROJECT_ROOT).audit("prod")
        assert "apps.services.security.authelia.oidc_client_secret_argocd" in result.missing
