services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    env_file:
      - ".env.prod"
    volumes:
      - ./errors:/usr/share/nginx/html:ro
    networks:
      - proxy

networks:
  proxy:
    external: true