http:
  routers:
    {{APP_GRAFANA_NAME}}:
      rule: "Host(`{{APP_GRAFANA_HOST}}`)"
      entryPoints:
        - {{TRAEFIK_ENTRYPOINT}}
      service: {{APP_GRAFANA_NAME}}
      middlewares:
        - auth@file
        - secure-headers@file
        - rate-limit@file
        - error-pages

  services:
    {{APP_GRAFANA_NAME}}:
      loadBalancer:
        servers:
          - url: "http://{{APP_GRAFANA_NAME}}:{{APP_GRAFANA_PORT}}"