http:
  routers:
    {{APP_API_NAME}}:
      rule: "Host(`{{APP_API_HOST}}`)"
      entryPoints:
        - {{TRAEFIK_ENTRYPOINT}}
      service: {{APP_API_NAME}}
      middlewares:
        - secure-headers@file
        - rate-limit@file
        - compress@file
        - error-pages

  services:
    {{APP_API_NAME}}:
      loadBalancer:
        servers:
          - url: "http://{{APP_API_NAME}}:{{APP_API_PORT}}"