http:
  routers:
    {{APP_BLOG_NAME}}:
      rule: "Host(`{{APP_BLOG_HOST}}`)"
      entryPoints:
        - {{TRAEFIK_ENTRYPOINT}}
      service: {{APP_BLOG_NAME}}
      middlewares:
        - secure-headers@file
        - rate-limit@file
        - compress@file
        - error-pages

  services:
    {{APP_BLOG_NAME}}:
      loadBalancer:
        servers:
          - url: "http://{{APP_BLOG_NAME}}:{{APP_BLOG_PORT}}"