http:
  routers:
    {{APP_LOKI_NAME}}:
      rule: "Host(`{{APP_LOKI_HOST}}`)"
      entryPoints:
        - {{TRAEFIK_ENTRYPOINT}}
      service: {{APP_LOKI_NAME}}
      tls:
        certResolver: {{CERT_RESOLVER}}
      middlewares:
        - secure-headers@file
        - rate-limit@file
        - error-pages

  services:
    {{APP_LOKI_NAME}}:
      loadBalancer:
        servers:
          - url: "http://{{APP_LOKI_NAME}}:{{APP_LOKI_PORT}}"