http:
  routers:
    {{APP_N8N_NAME}}:
      rule: "Host(`{{APP_N8N_HOST}}`)"
      entryPoints:
        - {{TRAEFIK_ENTRYPOINT}}
      service: {{APP_N8N_NAME}}
      middlewares:
        - secure-headers@file
        - rate-limit@file
        - error-pages

  services:
    {{APP_N8N_NAME}}:
      loadBalancer:
        servers:
          - url: "http://{{APP_N8N_NAME}}:{{APP_N8N_PORT}}"