http:
  routers:
    {{APP_WEB_NAME}}:
      rule: "Host(`{{APP_WEB_HOST}}`)"
      entryPoints:
        - {{TRAEFIK_ENTRYPOINT}}
      service: {{APP_WEB_NAME}}
      middlewares:
        - secure-headers@file
        - rate-limit@file
        - error-pages

  services:
    {{APP_WEB_NAME}}:
      loadBalancer:
        servers:
          - url: "http://{{APP_WEB_NAME}}:{{APP_WEB_PORT}}"