http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: {{HTTPS_PERMANENT_REDIRECT}}
    auth:
      basicAuth:
        users:
          - '{{MAIN_AUTHENTICATION_CREDENTIALS}}'
    rate-limit:
      rateLimit:
        average: {{RATE_LIMIT_AVERAGE}}
        burst: {{RATE_LIMIT_BURST}}
        period: {{RATE_LIMIT_PERIOD}}
    compress:
      compress: {}
    secure-headers:
      headers:
        frameDeny: {{HEADERS_FRAME_DENY}}
        browserXssFilter: {{HEADERS_XSS_FILTER}}
        contentTypeNosniff: {{HEADERS_NOSNIFF}}
        stsSeconds: {{HEADERS_STS_SECONDS}}
        stsIncludeSubdomains: {{HEADERS_STS_INCLUDE_SUBDOMAINS}}
        stsPreload: {{HEADERS_STS_PRELOAD}}