# Argo CD cluster secret — registers a spoke in the hub
# Generated by: make register-spoke ENV=<env>
# Do NOT commit with real token values — this is a template
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-CLUSTER_NAME
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    app.kubernetes.io/part-of: kubelab
    kubelab.live/spoke-env: "CLUSTER_NAME"
type: Opaque
stringData:
  name: "CLUSTER_NAME"
  server: "CLUSTER_SERVER"
  config: |
    {
      "bearerToken": "BEARER_TOKEN",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "CA_DATA_BASE64"
      },
      "namespaces": ["kubelab"]
    }
