---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api
  namespace: kubelab
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: kubelab
    app.kubernetes.io/managed-by: toolkit
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.staging.kubelab.live`)
      kind: Rule
      services:
        - name: api
          port: 8080
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: kubelab
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: kubelab
    app.kubernetes.io/managed-by: toolkit
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`staging.mlorente.dev`)
      kind: Rule
      services:
        - name: web
          port: 4321
  tls:
    certResolver: letsencrypt
