---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer
  namespace: kubelab
  labels:
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: kubelab
type: Opaque
stringData:
  api-key: "***REDACTED***"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: kubelab
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: kubelab
type: Opaque
stringData:
  password: "***REDACTED***"
