services:
  wiki:
    container_name: ${APPS_PLATFORM_WIKI_NAME}
    build:
      context: ../../../../apps/wiki
      dockerfile: Dockerfile
      args: {}
    restart: ${GLOBAL_RESTART_POLICY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    volumes:
      # Mount docs for hot-reloading in dev, overridden in prod if needed or kept if standard pattern
      - ../../../../apps/wiki/docs:/app/docs:ro
    networks:
      - default

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
