webhooks:
    slack: ENC[AES256_GCM,data:+aAXwDOK2GaXioolK64yQ3LyPX8BBpkEqzCS4A+ozR4c0kPXQ8r0mPwpXO276enUCvE725Xx6I12LXDOKIjdsUS6Vat8xdD8IM+Kzbica7oP,iv:g0+jYKGoeR9BOUD5T/iheKxOtKw3DsoGPb20RCMjl+k=,tag:9akLKvBL9P5TZBzfqpwP5A==,type:str]
dockerhub:
    username: ENC[AES256_GCM,data:pKfHGAsVtfvaUMk=,iv:4TzH9391xPcq8GchFLTYWMfua69pNyZtCWuvqjDafr4=,tag:Ok/4F6+LGHfLlomlcRFxMA==,type:str]
    token: ENC[AES256_GCM,data:hPw4zVgSH07Fo2ts2HU0DR5DXb4U6uOtjTcxt7M2O/01ZJk3,iv:M76Oo+2lRnICLsduccs5RqbaMVvpr1Rb36wzXeDSqaw=,tag:hLhscg1VlbX5DDPxYXSTXg==,type:str]
hetzner:
    api_key: ENC[AES256_GCM,data:JXger0E9e4bsJHfFnVK/LTlaPSXaUtDajJEhvqB8EIml8BWD6EG8hTUTyFL3vuWVNrcmgLZR6V0z5eSYwjLafw==,iv:N1h8w8z9E8p1gXHPAdslQgAffJwoqyVmZzqjsnJKSNI=,tag:7MDEMnQ57qQxIedIEG1uUg==,type:str]
cloudflare:
    api_email: ENC[AES256_GCM,data:OAc4tjFB4SRjb4U8EA+loJqIu+eE,iv:8Rm+7sTT0CsV/gDQ7ShiN30CZAo7QPpFv0b0+JbTj0U=,tag:IFPzgcKmuBaEW0JlP3rGPw==,type:str]
    api_token: ENC[AES256_GCM,data:/im2ae+y5frSM1iN6bPwsR2Ktr9VcnA1RZy2K1+bQLlWjSQ4F1SUQUj5+lexl8aoTAHGybc=,iv:hhOto4U8XSSTRcGeisYk2021w1i5oTiyQI3wOASZftU=,tag:PJtznYhJ6gnHGnCrr6xckw==,type:str]
    tunnel_token: ENC[AES256_GCM,data:2drpaNOjlFsd1+p1hBg8otyAQjBHhu+cgEMc18WNY2314bHZzyJY34Nl7Aw9MTpmuOz9h3NPWAdv6ojlFvbxdNU0axzL9LPxB00xfv540DFqNngHx4tnC+4iPg4CotUX0c67lkKSl7oLLSOfkiFPW6CNMIDkeZ/1o9mn4DxfHnuPMySt0UXVm4g1OMQoMoyQUmmZYmlSJnOT0vSFV1uMwHgWb1m5ZVeLYzjscFna3hLXHh3m0BDIMw==,iv:zi8OK9cI3H7xqHd+BeD3DM4whUS/osEOhcE7hnvMhTo=,tag:VjPvEKaVKjcePQFythVSXw==,type:str]
apps:
    platform:
        api:
            email: {}
            zoho:
                client:
                    id: ENC[AES256_GCM,data:fWwpg+wFi1+z+rov/W6/sHboUS8QwXLSKr+12VDd8bjBvn4=,iv:pO0TOumUfClGI9tLOX8e5+Ew0Co2mBLG9GurILRYJ/0=,tag:qA2dsi+NBPu3WvMFH3YeSw==,type:str]
                    secret: ENC[AES256_GCM,data:pMh8nLKpGyqTL0OaOxagIhlILdyDkItX+ymXzRWUKsMSYAiTMtxlU28I,iv:HGiWIs6ctijCovi/jLZQMHF7abxHyGYDol2kevkRwUQ=,tag:f3YE1ZqKk6vkPWg4VQxqIA==,type:str]
            beehiiv:
                api_key: ENC[AES256_GCM,data:Jr3z4rmGfSvCqWq+bPIlpEwp1xMJoQBEZHTSr7Z3wI9qQnk183lQjeScNJMMJ711glZkllhSBZmNBADCo/M35g==,iv:2jBxGJGw4aizI651ZsnAvyr1/X43lCo3lde82FgNoEs=,tag:KwUb3rWYDQys6KgrzsfvIQ==,type:str]
            beehiiv_api_key: ENC[AES256_GCM,data:H/TN8j87gS/ujBhLeso3vD2gCVRcPB0qqFlhoMQS0WVqigXQ3xQcbqHE5/RE5cuZ145VybHusvnlA6YgsSBxQw==,iv:0qTT/gjzWB1uPSzw/EwTPHdLGHTRJ3mKBIK0UtyIOAU=,tag:/V9ggS6/09cbceGPkkF+KA==,type:str]
            zoho_client_id: ENC[AES256_GCM,data:b/JVKQAXlWNCErrCwvcW35KZGnurEteQw0Msang7AIMktsA=,iv:/xuQypgqr0Eg1ak4u2f8iA4dtlETJW8Js9a8S4kH7eY=,tag:BTSCrpI63mtU6pdmhwvnGw==,type:str]
            zoho_client_secret: ENC[AES256_GCM,data:FfaYExI+tSgXZKiphdFWTpC0LxTe8FMmUw1M2EjOMIonI41Wp4CbCTRH,iv:F+EALTsY9pcVLWu7JlV4jHn62/tsq3OOEQfj1uSnkqA=,tag:qmb4rPv+BDOiiuBDLLqzmw==,type:str]
    services:
        automation:
            github_runner:
                token: ENC[AES256_GCM,data:d8d4Qy6/Fo56rC2Ia8dujiLeZC+Kdsjr283nbBcMscGvmtVljL5qNA==,iv:azmh3FwpRFOQSR2LOzHcEgjNSoMEM9RxJAm/HNOPjEU=,tag:qat5pb8V8z9nG4kZw72ueA==,type:str]
            apprise:
                telegram:
                    bot_token: ENC[AES256_GCM,data:om/rCLSEMwhif/oqXZrlARE2Kze3rLliR/SqwHv+dqa9H8ADAdWG7KAnOMs2EA==,iv:cIzwFHZjarboHO3jsTfmfRPN6iP2uY3dgnjXg8zlZNY=,tag:QCP7AKjBblZbTYzWf2uYcg==,type:str]
            dev_node:
                github_token: ENC[AES256_GCM,data:saGo4iDZulPTkUVp7+NCZqiVgKgpRm3lyPwUwv8tnvgzLUTGSKACXGoZIe2z+TD4U04UGjxcHOQywNzkLMVkw4UASazHMqAEQh8ORIL6E8AoWYM5g4Z1X0fyIbI0,iv:usTGvCtQHXt2+0zhGilY0uM+EGHOSsnbYWno8bN/8EE=,tag:iKeoCAgPBycf/A7Zd/ev0g==,type:str]
            notify:
                fleet_webhook_secret: ENC[AES256_GCM,data:xgZLwr1Se5S0spXxWSGGlpBDuHR6RPqnQgLSKnrdF0gIVaLdnWXScZOhZAd+9WtdxNUJdlEjzylC9f+EJ6sH35ss1iLCFvqshzSNMctq9XsOhI2es0U=,iv:8kFKcW1w6E0wR8c4S6ZCDioJPXFPrLQL78HYfqCjsbQ=,tag:EUY4XalL29Imm4Qo8JzI6g==,type:str]
        security:
            authelia:
                oidc_client_secret_argocd: ENC[AES256_GCM,data:cWPHYXaMrMORDLzyFjG5zgcTB0jEPYwLUQMoHa/+2BjqHOR5nPkYLyMcvje0k2yyUcc8a9BH0U7ymaKsYdguujgutf6cZrnkQGXiYIzfVRyxk5y65Ck=,iv:z4erV+TaNKqkG97g/6DvUtDEYkm/d1oRL8qGelZfAtM=,tag:4zO4h4f5Afep8XX4PDj52g==,type:str]
                oidc_client_secret_argocd_hash: ENC[AES256_GCM,data:zVxMdJWsPnvSxWeC6ctCUj08mhVSAJmxzOv1oJwsz12s+FvvhtKUMDVARMi7SIIqqPOi/xx3gjJkE0wj2Gss57/xqguAokP+NMOEJUdCTqdoznLVUFaWgIbrC54MNgZsLA==,iv:hLZc+hAzVGjtStQNM7g3+Dqpb1r1nYAsRpwTbH5P9Z4=,tag:DWOLFkloSBcxStffP4cYGg==,type:str]
        observability:
            uptime_kuma:
                api_key: ENC[AES256_GCM,data:Y2o8PUMp0tkJgW/Gy8qLiY7M+f7vC5I8TlHR9QApQxsyKOVxqidsDRKn+Os=,iv:wjJaquUZaAVG1WRssu6nbKDrAURVCt4eNQnKvZp13/E=,tag:1ZLbcv0CUmQYU44zoij8PQ==,type:str]
                admin_password: ENC[AES256_GCM,data:kEZGri9dp8h+oI10g4mr,iv:8Q2n4fKUZkd2KFbMlYu0GNWuMN2BSsNzmYVn5OYJgOM=,tag:gpA1tEwwEKeRBvPqzz7tOQ==,type:str]
                admin_user: ENC[AES256_GCM,data:G+Mc8A==,iv:DFLnI2lJjAQ+VhbDntMynp6NvMDbYjujhh7nHjgb3r0=,tag:LNNawEw4txJ9dsJVBmSSUQ==,type:str]
                push_tokens:
                    ops_backup_node_beelink: ENC[AES256_GCM,data:b6IGMTVXjYMxRsmBxGF3Bl7h6voJ3HQFCNclQIcRxujHq11W8k63vE99Yg==,iv:VdHPwGo9NTMQUxPierOrfgTclu7uyeVTTZ5qw5MmvW8=,tag:HM/GAe0qvJ72hDl6AxZK1A==,type:str]
                    ops_backup_node_rpi3: ENC[AES256_GCM,data:D37ybpuUvpQPPsv3CzFQljeHSq5xmxvfO+isVAF86GxJI1G0DMV3jw8EDg==,iv:MfLSf6/nMo2MSJJkn5mt8QwZjlD98m6CtkUboeQmTOY=,tag:mJxj98K2j/MZR1ZRLs4nvA==,type:str]
                    ops_backup_node_rpi4: ENC[AES256_GCM,data:Uw8MJsM144iVMhnZF/FwRexPMHqBrFjKmr/FJRb1zzGZBv2mcINv7tq3Uw==,iv:DyvZtpqG77cyiXMjGDltOWfuT/EVmVoBAztWgT3+GEg=,tag:NWbUfzuyKziVlclIiEaBSg==,type:str]
                    ops_backup_node_vps: ENC[AES256_GCM,data:UGufThafBRK1KuIDswcpAr7x5opVcUhUcb4aO5bLHdVhRn8KuWKT5+C3HA==,iv:JR520c5UaGLq+/J3DpvhoFuaf4xPzL5/CSF21qZH09U=,tag:Q9IMjC7hc5JUfxzlg5hhaQ==,type:str]
        dashboard:
            homepage:
                cloudflare_token: ENC[AES256_GCM,data:Vz/2Ot/dzKNFYSfvh2a7M5fSSfBu1tFqxUBhzZeFLIIUpwc4oFG0Le18Q18r9FQM0eduKSA=,iv:OqZPDPGI7A6lmQjVQgMx4kzCf2omOAglRD5yz/KKXf4=,tag:/bwpJxjQ5q11CNGa89Ry3w==,type:str]
                github_token: ENC[AES256_GCM,data:MM/pCleLlIAbNGk2spewm+hvyKOL/lZVX1Z8uXScaTs4+B3HlqZE2w==,iv:YRlPWeGjTfDy2lu8BoDooXelKT27makiESwm9itWkYo=,tag:ue/e+Nlj+aGRTJ0IIwivYg==,type:str]
                uptimekuma_key: ENC[AES256_GCM,data:CBrNrPYlOSQ5mgIb6VPBCkr96KSOnRHj5tXo/VHBqBbMIBfiueUteGef76g=,iv:qlDMXx/5GjZ5U6MgQ/6nzRGV14hnsgylhYQ6qMUK0Is=,tag:KG7lOIjLWSNmKA6AKxwtyg==,type:str]
    testing: {}
aws:
    access_key_id: ENC[AES256_GCM,data:IHirfTGiAfe5X1dM4Sb/Z7qs4UU=,iv:l+RRhqek0DhnqG7VK9MngSGkkBzVOrYmgrFTgni43Ks=,tag:WsIRnLB946VoD7UfNKOpsA==,type:str]
    secret_access_key: ENC[AES256_GCM,data:FZnl6CK10xClFh5dOF53M/I9AG9ux0n23oSKyHRPAfohO4XkrWejLw==,iv:DW5ygJmilzG6DdwPcFgyDQ7vXjxAoqtc80osyzGJdI8=,tag:tZ/R1WsImlSGw0NWaFkXLw==,type:str]
argocd:
    admin_password: ENC[AES256_GCM,data:0Do7qtpeFWc9pj5jwHcw,iv:FHRF/d7eyoTV5UzTPEoYhsMrqXuUCPgu13McShFr9nE=,tag:ALji0Ucf0uVudpZNDGeTrA==,type:str]
    admin_password_hash: ENC[AES256_GCM,data:9tI7DKileGrZ358nIYoqnKR5O95X/5nBhojhfYthq91MN0E6bXZOsP/csTV1ynFTkIEqtoHGnZL1aCq2,iv:DefudYmwjfwlkHm55arO3IziFICrC2eCRjfyeFJQnyc=,tag:TePrg5BKCdhqF/+VkPaPdQ==,type:str]
    slack_webhook_url: ENC[AES256_GCM,data:EESW0dK4503q/lRHfPYrSEttJnX1Z4WKVfED2uvrFGvwMvpyv4XZq/EZfcTo4hrTn6mrK167Ec05ecVOcqPIumeLpJVwoik7PIVQ7Q8j6DYf,iv:XebXsG8xMdj4pm/TW5+AJnXfNUPFsvorJdYG4CEl87g=,tag:NtQvlIz7j0D3775r9RJSOw==,type:str]
    github_webhook_secret: ENC[AES256_GCM,data:rQpwp4ndUUN7WTyEAucC1cjz29dByRs4L0927JAc1WAfpkD02o/TP90eIPv6WQ/K8j3c8uWXVprYh+oa0LiI3g==,iv:Mabgw27XQ1RN91YAHK9saIyqJCjGcPKyqX6S7FZ0uCE=,tag:oKvOmj3bYjreWJ97RbnH1Q==,type:str]
infra:
    smtp:
        user: ENC[AES256_GCM,data:oA3RJ1E9LoKA1uUZxIAfPixhEspz,iv:zUsVtg1QU6CUe/4gOXn+FnwB9732G81KH0eh8yfgbeA=,tag:BILlylHZBn8vK5dQ1aGslA==,type:str]
        pass: ENC[AES256_GCM,data:m+RyfURcO3GJT3UQL+oVd83BGg==,iv:xNmpbk8V67cQK5wLLlG/iLx2+nf6ApGrLhr+t/eKHEk=,tag:IRJSl5UBHR9edwUbuEeFrw==,type:str]
backup:
    r2:
        access_key_id: ENC[AES256_GCM,data:KV4ivpgFmveqkT5ghKkexo1w9yMO0zbqeBfTJJSJOxA=,iv:NFM42SVuXPt34z8iTLGjdSTyMdBAXIQObhEOevO8fIc=,tag:c/mUT/2Bah3Jeu0KaTv/8g==,type:str]
        secret_access_key: ENC[AES256_GCM,data:qcElC3Uo6NqPifnICYkKowbBJtPyYI5KFwddREDfapOdoZRb3nrhbU0Vu+LkT1+tTElF1XoN5UkgnfnNUlQZTA==,iv:J9RBvx2ZRtBXb3CMHxm36RI+vzO39naylEO0DllpLhc=,tag:EwxUYK9GHgE+Q2b6qQMzMw==,type:str]
    restic_password: ENC[AES256_GCM,data:s2J+jCVuw6x3EYIIztl6iGstNUL5SnwslI35JscxjFFlX9pTCBvy6cY6mMCkCxIYZUyyz14tvFM8dqHs7uGzng==,iv:7sQxoO3SdRpXUOwFt5UwMHZCA+fUjuckUqBIgvLMk6Y=,tag:qz5NgIaCXSP+vOymf4qnyA==,type:str]
gcp:
    billing_account_id: ENC[AES256_GCM,data:5DuXVf2y5gkQW7KNcKUuSZw/fng=,iv:jYbhdW6ckNVsMKAhawPO/FEffkE91+eF8EiBH4eKapE=,tag:btvvkUo4T0NVI7gNb0H4IQ==,type:str]
    headscale_api_key: ENC[AES256_GCM,data:DJfdJP8sPymTC2IzYRsdhNFKu0MC9TOACJLoeBtXpR8+MVMExZByG6EXT21OvWgwIqibSnJPtuNIl80YbD8PdYWAn7L19AVL9xsrutiIDF9tXDoT+2Ph,iv:MEF4m4cHGO+UM+zgDXyNsVJgXOZlHecRCUdSOpoNdRc=,tag:/PShV48C45OHx1trU9Ck0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcm1zcnpzb2tKVWpReEtG
            UGNTZkFvUTdTaDFrRkdmSCtvVmI3bGsxQ2ljCldObFgvNWw2Q3F0bkxEU3VPbjcr
            V3A4VXZvKzQzdlU5MVdtbE53bUg5N3cKLS0tIHhYUkRuamhibk56Tmd4dGpNa1Fi
            by9MZ2p2OHZvdDdxNSsyZWNGOGNjVzgKxYFLNgq+nIK/JVrNWy8C6nmUK/ZZQpZ9
            UfIyAn9uJQzZrIg1tR153yZkuuRWwIWoyN8TfIApIdKzqyPNo1EpUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age166v8efpskctmxxes5lcqpxkj0ny3q74l3v0pswpdpa63wlkqmc8q35fkdw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYUdRWUxRUWJHMUlNc00w
            SDBqUkZTVkltVndCY21zV3BadzkzNTFiNlNVCnhUYkFIS3VJRXZtYlZYUUJqZ2oz
            NURJaW1oOFV0T3BNa1VUdnZYTXExd1UKLS0tIGQxRHN6emF2bGVIZHNDMDJidVps
            T3ExOUNtRWo2aHFScUdQN0hhRlo0NE0KE4s+2CT1WNyu7Kdn+evEYZcRMVMbrjbk
            WBM6D2Ytkqg/TsPoXl/cUi9PrJKhqMihDM5svHn6aimaYiHR9ttTbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wpqxa7vqkr6watypd6zlw7kspz506kq2kvluxnluhz72mgtaga3qlg84cv
    lastmodified: "2026-09-03T02:46:32Z"
    mac: ENC[AES256_GCM,data:8RHrDgnLKW1tfZS+ZHcFuq6QbDkEZeiqRdOft57OFNQaAK/vnGZLGzTDuFK4F2gIOJLlCOs24/ZIepWOyXvoUxSyuYpUtPHYyALwS7JD37LvHacRm1iv9rHamUdmd1e9RdXyzqg4Uu0eyJH7aZHTDK0H92vBSbNSgnZz6xy6p5U=,iv:aGwFz554lVBZUdwuxTHy5kLN8RHhPqwz756WYToIJOw=,tag:j3EnmmO8yIgTLaNj9ZvCUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
