webhooks:
    slack: ENC[AES256_GCM,data:vqSjsMSC63iLK4N76Q+ZymH/GXe8/3z2oiQPkyAjmkppwHbwU4HSi3rIekeyTvqkTZVtMq3hlxDkAvfwg94YYU3a6SJj2s9BtsVf38tOaSnt,iv:sfzQjvcnYBnlgWSRCDxxxKk0D+w3lahmEpayl+0O6fA=,tag:JqwJ9Y5qwzPvZzsFLlmI9g==,type:str]
dockerhub:
    username: ENC[AES256_GCM,data:PV+QoTNyo0NXN30=,iv:7w3QICr2HcaaeMbFH3AgaMhRycFBKV+ptTVr8AmR738=,tag:FoPIFD+TsYPekeyRkd07aQ==,type:str]
    token: ENC[AES256_GCM,data:8ZAwGrWE44SrEYPqsaTsMCp1tMKVgtP+I7HQDzNqxKkHhtTF,iv:bEwZxiHO23GnBuznoq28J8TTSCcAv6F4EN3LRBpNf0w=,tag:0Ybo21WJeo0bgyyBildM7A==,type:str]
hetzner:
    api_key: ENC[AES256_GCM,data:+pGaMk0cbMf8zeQtSpp/ZCn0QT7o5jWiqMvKObkzyA0qBWfNTywUBgu0dQIWjr7QpdhLvpVHsGXu3/6A1RhOFA==,iv:cvHksz13bQsam8L6xnBRBQD0lXQVdLT8SJaUzC11L24=,tag:ObtOg/ssF0+N6uL+spvLnw==,type:str]
cloudflare:
    api_email: ENC[AES256_GCM,data:AG+Kko3IW2EC0eI2o/Eayk7+4VWK,iv:d8TlfP4EBtCMk2FIj/8pTrjvWkHB+t2eOh0/0XfVES0=,tag:puSRZzm+S1/Pu247lOf/nQ==,type:str]
    api_token: ENC[AES256_GCM,data:arYYRSj9PifC+JVEdKhj+m4E14doVZU7gjihpbdfj8gjCEehWlS7iRuRxABBlqZYK9xSJXg=,iv:eQW7GOTQlgZsjjKmk8MICvKqdyAxsaD9yObErey2J1M=,tag:KzQx7PFGQCfOLb2SiQqRjg==,type:str]
    tunnel_token: ENC[AES256_GCM,data:+dgwkwHy/K3hh4fENnzi4/QW3/BCAM0j5jzUBCbKY4nLZiz8HqQccq9AQkV2/beGOi0gsj9t5RABodzUA9Ye0ghlZNpGSYZcnsiSvbMikzvO6JcYV4iU1D19pk0Nd4Uqq/+ho2zhEOK0KqOp3kv9OfrjyZJzibvjfBQwZiJ5YVhPJ3mTWvs7mZP9SyvGgiW3jrkHYMvEsUMKZPRn+hanKhopsYPjuCYc2CoKGO3gy+durjSCHHg0qw==,iv:bEKBX/t/irJYqYgQ9k6NcUQ1fLRklv071I4V6ohxHyw=,tag:KqLvfQFS+SgOcU9PFqLx9Q==,type:str]
    r2_admin_token: ENC[AES256_GCM,data:lVxzU9iJXRCBqrAg8VgsgopdaT2x+LN0Y0l0xedtRQaKhEOlU9E+4JONn2GPerrHUBxpARk=,iv:io7FZ8tvg468dV6qVn5KgX3SERP6uz9RKmwpAvU+9r8=,tag:J8c9ZG7r9pRziynd+D5rTg==,type:str]
    r2_token_minter: ENC[AES256_GCM,data:6r77wl/u7ug75qj9pPsXz0iDnZ22hsw85qrYS1UaBAhBKpDvquIc5ddvzVvwG9aYfGqgnsg=,iv:cDlLy8MnzY6zpc4fMAZqEdEIt51TypfUL6mNvDkr8Aw=,tag:855d/U5Z5NlW/F3/mOo6Lg==,type:str]
apps:
    platform:
        api:
            email: {}
            zoho:
                client:
                    id: ENC[AES256_GCM,data:mRekmq0rrduUEHDLyyayIjUzHpz5GdXXj7onAcTqbICFmic=,iv:cY4whquQmvLfSU6HPJb7g9qJZLmoIdfIHDkHqF9baic=,tag:Foz6mjoQLrQiPCn93FW8Dg==,type:str]
                    secret: ENC[AES256_GCM,data:QRUff4XK6DNZMugAz9syE2NY5i2Txzt5L0q8wyX+PSE1BDC6VapFHbVP,iv:viqVPyykKeU2Ogk/29fPr2AVGqbc4igtMAQicT5q4fU=,tag:RiHilphD4MSBO9S2t5xxJA==,type:str]
            beehiiv:
                api_key: ENC[AES256_GCM,data:2LW0GScLmARNv/6WaAA78kL1Ie9/SyLocBJSlREBxh7tpNnPDFhtUhUnuIvtKVpxpWVNsm34zMRZidUuZMN4qA==,iv:g/ucZkS4yqOBHn6Z+nvVpsb7/KkC+ntj3wqRHDkerdY=,tag:mPt0I3fFgSTJK7ZSVM1bXw==,type:str]
            beehiiv_api_key: ENC[AES256_GCM,data:9BdLm2uL1VlmR3gcvKWywK9Mu6dKeCnou+Qs3JP7ym88zSuQ+GnJQfQueylLwpEh1nxxRmYyJDfy8Qag98tyPQ==,iv:GAShgiWzVv5qqbizgSs+40Aaca+OZ2PtSg2mepDwCCw=,tag:5To2CseigMQJXn67rXXv4g==,type:str]
            zoho_client_id: ENC[AES256_GCM,data:5bzVaZCMGYuXi173QYeR0J2+YyQSe7b5rymr8i/WD9azRRc=,iv:EALz8aZG8qI8lXiP+ulRrlmV/yJX11Nk2VkL1rCUiso=,tag:Hunp7pGkym7lDsvDKfAI8w==,type:str]
            zoho_client_secret: ENC[AES256_GCM,data:rAhayr5Vk3/7EfOOPRlKUmOh06aHZZIj6AnpZsKzTvOLo9Y0bqRKdEQS,iv:rWznl8+1TrYM+RyheYFJZpctqpujskAd6qFswUkLQAo=,tag:cXeurleCV3SU5UtP59J9aw==,type:str]
    services:
        automation:
            github_runner:
                token: ENC[AES256_GCM,data:OMisIUM9ancsM+JsmXJYJ3+G4QKGtYlVWIgKRU/FstMWRy00UNAcbmQ4NZjdc3x1m9gQacndxppP6FvoZrBOBReUK0yW5dxuxBD6swDriL/5iKdVqLrlKiep1fyY,iv:8PyAKdqvuD7dKT7Xh3EgwDCo31xGMgaTpeA3gtI5U3E=,tag:ZDAgk42Nys5SMimsYmgMVQ==,type:str]
            apprise:
                telegram:
                    bot_token: ENC[AES256_GCM,data:f3uKFjfM6+Txv72qSnQoOfhBAVxlWyid3LlD/7b9Rtzp0dS29wkdjR6InNFI3A==,iv:ql+cjdLt7kx8VC1Pl18rfUl+5fHC+5LHq/cYAZPdrGo=,tag:I0ehmBEhIlJzcwlExX9knw==,type:str]
            dev_node:
                github_token: ENC[AES256_GCM,data:foqQ7GFI2hP6CHmvjPfYUFMS5fyzqdaAQgwgm/mmABSqkeeR4757BTQkmkqG1tKv5knsfdzApZbg2U+UIzSjtVZAlFj211EzHhdy4ckNBhc/Iu2YYdYFGUWww9k7,iv:rQxHrMGGH6qXbazoKMXtw7YvG3fc/xkeJF92Z/Gu+Y4=,tag:dyJ+Sarfgmf/vZj6B9PYWg==,type:str]
            notify:
                fleet_webhook_secret: ENC[AES256_GCM,data:ryiXqATyAlO6K7gYcCcb7O0N+vuZ20GROBD5tL1JDddZLYir3NbJG/ZpqSUekwb0XpCBeRBex2762lczGAnGscG585IgFKXdB5d3SWTTRcpdEErts2w=,iv:RB23sy0Zadg25oXaDbw6Qa1tZeT/N9P9a2OsT0Zb0qw=,tag:bckAxnZnXinNwIbgftKE/Q==,type:str]
        security:
            authelia:
                oidc_client_secret_argocd: ENC[AES256_GCM,data:9soZ3pcWIcmIpasG31Lhchj61h3OqYB4E1AVJdgzF14f4TGHqidivGemmxx+ZNEEomh92kBGeZY59/0wJWzzkUveiuOKZmLQ/TRYS9JOPnSPyoxZg3o=,iv:LlnhPXDK/QFT3WhpPB1QnrVM71jlR69+k6onMLr6gHw=,tag:jbUXZzQRLa+vjlvretjRLQ==,type:str]
                oidc_client_secret_argocd_hash: ENC[AES256_GCM,data:WtlxgyjhxLWFBLk7Ca4MfpA/XRzOJwfzvcgHnPyoSDuCAs6injOwf2+hcsc9/yrDvjSzMWJMk2yXYa8KUdaWajK3lUiB/HF8QQ1WsTt2QB2Cmd3DDoJGCujCK2WdSFEBOg==,iv:NP6cXu8aCcNbacaGYE1q94nOGiqgBV0ErHLwJ8piI4w=,tag:ap8BPoq4BLvHPoGhoLr+rA==,type:str]
        observability:
            uptime_kuma:
                api_key: ENC[AES256_GCM,data:g1uC5WTj7X2L0NRlAMr0+dS8J8aFyAwZ9NU0gZW8o7ku/GvVdbP/lhTcFzI=,iv:gpuIZu4/bhrrvFT69PbWST90/5SlMW2nLJwD7/Bmw2g=,tag:DnTreE5bgl6NtPzZkV8UqQ==,type:str]
                admin_password: ENC[AES256_GCM,data:9ad7KqlE24/6z5OqYSt/,iv:hJuk/h0htK5jHp7lr/lgpAPkABOmPrYED3SLpYmWZBU=,tag:/c/krvtsFKhUycGdSHXi5g==,type:str]
                admin_user: ENC[AES256_GCM,data:VXQAtA==,iv:jmoRC4mjpQPLgrTFmkDHiGBWmcdLipYhpBc7bINRMUw=,tag:e6aBCqWKp3J79EdQqseW7A==,type:str]
                push_tokens:
                    ops_backup_node_beelink: ENC[AES256_GCM,data:CYg4EJwdKUW1zu0wIwR4J/Vx9EuGGmZ87awVbHE+kkamYMdIq1hCYsxqlA==,iv:zOfc0933lRBqVlMXxQaRtsHeF59uOOJRdvl7JZptPgA=,tag:iTAnejjfB4mAbA4UOfDm7A==,type:str]
                    ops_backup_node_rpi3: ENC[AES256_GCM,data:ieXk8NuD+GrTEzjgTz3CkpDs3vKlNXRJIooPNok71J0iTm3HGJLh/3uaHg==,iv:q5/nDb2pwVfV1UeaWKi+Ol3MglA98G6/EgBYL9UiQto=,tag:0HXu4kvIw81mbLSJm3/BOg==,type:str]
                    ops_backup_node_rpi4: ENC[AES256_GCM,data:ShDv1EQ9NfsKsHa135kr9mSWkiWhUIdGnX9gyd3IUHBP7a+m4V/TUlrVZg==,iv:LfWkeEEX0ldviRYB3F00pGub5BgRBUclz2dRSB5zaSA=,tag:JtfEPewYZXLfP+m5pYbDfQ==,type:str]
                    ops_backup_node_vps: ENC[AES256_GCM,data:Y4IhCQcbefDjRmEI53U1g6CzefQY7owG7DczSB34THL35lS52u7E4Nw5Fw==,iv:10v99N1LNLZ5gNOI5olfa7arQ1DPs5oZDSU1fh8PByc=,tag:l8kbK85h032qyjooYXEsJw==,type:str]
        dashboard:
            homepage:
                cloudflare_token: ENC[AES256_GCM,data:G4B8dZm7MbKuMuogupO1gLCLxGKn5wWBHSSyJVf3zDk9Yq8jICV/w8AZmYnxotxZ61yKgA0=,iv:7wImmsp2aQgE4bd2TUGUlNj1uj4hSMzA8W+q+3EAdy0=,tag:btq/m4GOYfH6ILt/rIHRVQ==,type:str]
                github_token: ENC[AES256_GCM,data:VUDKlx3Vw7zRN6Tzd+Ly0KHA6UXJ9IQ+vpoyrjgMIkbkIBvJHXoNgQ==,iv:BZs/OlvYiILvu6TycWhYZ4nMSfcKXcV1dyj53gNtcRA=,tag:8FtISGgP4+X8Ba5LG6Yo3Q==,type:str]
                uptimekuma_key: ENC[AES256_GCM,data:k0KCImYDCybrq3w05WPgzh7Gi+dfySNXTh6Vk2ovlm3EOPDKYvFyXmg6eVE=,iv:3hFik1cQa9rn20bqp22lDwhBGJYbb0Nr0DQme1jeOy8=,tag:JHxLzs/K59pHX6rXjeHT3Q==,type:str]
    testing: {}
aws:
    access_key_id: ENC[AES256_GCM,data:YG8xEsSzwx4SYcX3lJ3+zNWjddA=,iv:8uNIs5qPzD/aWQJahSfvvAgN1xeoWzH4I2LoBoGNkSA=,tag:f8XvlL/9JjUupe4lVJrMDA==,type:str]
    secret_access_key: ENC[AES256_GCM,data:G+Rl6DC8Z30V+TOqegOPfsyumLcTn9Px2klzUUSH+UkHr5BorDOo5w==,iv:WVo2OFZfTxOrjv0IfxgkOyLmrGa/Gau7zKVFNBpUuaw=,tag:egUrRWzV33oWaA2NTtt9FA==,type:str]
argocd:
    admin_password: ENC[AES256_GCM,data:hcIOAbLv7+6JKtwPDKuD,iv:1Zax/aCDokDbOQSTli1bKXjdfXkrVCB8J1MVcB7WGm4=,tag:0fpETGnsg6UxB+6KZgvZtg==,type:str]
    admin_password_hash: ENC[AES256_GCM,data:fsGmDm8c5HsdMvSp+me0NOYCLe9tpFHXtF1/1FxHB3jaK2wtpmbOtB05q9j5yqZT0eEQnBsJmeBIhiI8,iv:oLYxAwG3lWKiimkwV17ojxNFOKGsnRh76w59NNAqpJE=,tag:iF5AYoo1VAMR0/uD0YXI8Q==,type:str]
    slack_webhook_url: ENC[AES256_GCM,data:NXZawkBSUiBCWDBMarIDGUrNOHKxpME1+zHA7MihezUiSvhtjU2PpgIEGUTcFq7nsySh0touH6Ig5NX9/3B0RZ2bCXZEEOv4g0vBYGcNM2Gi,iv:Hl/aHROhWNxZkrjPWF0ua+V6l1B9OOn72C503A6gK/Y=,tag:jA8/FtUsJzzRMWW5qMefHQ==,type:str]
    github_webhook_secret: ENC[AES256_GCM,data:cPhq02J61FNTAntu0T/cqPkd08/X6v3D5qdPQHFT6NvN4bWdPad3Iqneg6k//zK/K2YerZEFUbN2XvpE6sVtOw==,iv:3GBVx2UNT6WZ2+pXhkQcJmSKNNkkOYURYjlbjLFjUOE=,tag:EE4uVfPxeah2QKK6Oxc80Q==,type:str]
infra:
    smtp:
        user: ENC[AES256_GCM,data:6/pxbtpB5U8g3t/ecQC1e1pNROaf,iv:03yTcS4VaHf/8Jm3NC7JA1RsrB4hl7pxXgEzQX6XCqc=,tag:OJEYSZA9AkPZqwDLT89CDA==,type:str]
        pass: ENC[AES256_GCM,data:tuSgbgvhOxxns997tH1aDiC8ww==,iv:7/LGoh7NBj9/Fe8bl7PjvsDPPeB0AJQFYCDPDAQ/Vk8=,tag:dgJVTuYuOWhkd9z+VoFALA==,type:str]
backup:
    r2:
        access_key_id: ENC[AES256_GCM,data:AhRNGgyU+F3Fe5xrbgg+Sv9bkXZ+zQ0LFwKx0RD3Ecc=,iv:gdklmBoY94M4BndxGRQWpJ5q2Ro4s3N8z1LBPAvy14g=,tag:q7/KWwwIljlqXugVXSqrEQ==,type:str]
        secret_access_key: ENC[AES256_GCM,data:gYHzvhts9PSfeip9cQ2rkrdwwC4Nf7TOD9ftwnpTCKEACLaOYCoO8SY8MD9Y91vBu5kxljhb/jVjueBR483Hig==,iv:OrY+hDEX5Sil13xuevD49zt+8WMSBWOUWyVfQE+LVFU=,tag:kfL43QgQ3sdpEYC7C5sR4g==,type:str]
        readonly_access_key_id: ENC[AES256_GCM,data:s/yT9mQH1VoMLG+QeAggn8+30OTBWOAlSNyKK+2UePo=,iv:znritq3DE95kr3su9nBsvv5JAHucsZGPdRBQ0TnaGqs=,tag:QYsxXQqrCcWdJJagz65CRg==,type:str]
        readonly_secret_access_key: ENC[AES256_GCM,data:BKc/TqySBYjBG4VEROBGjQERcHdVbeWDnb2NFUr79L3IeRJvmJojZyL1anlLWXZsYLw8HtsV/ui9zxFmmY2jnw==,iv:KoTJN1dg9rusOCvaRysb9zEkICBjf3mFSIpI6OTnZCs=,tag:p+LRBr6RD0b3ZDa9bXjt7A==,type:str]
        watcher:
            access_key_id: ENC[AES256_GCM,data:X2W4EYYsp0d3ek7lg8BEcqbF9PyG6ypv/MCYrLBuMZA=,iv:UJno3hcmGRMtXuiPsoBorjBYorCwPjgxAPeggU9wAG4=,tag:PoaxVyEB0hbMKqC18XGQ7g==,type:str]
            secret_access_key: ENC[AES256_GCM,data:GYHiT5JNsnMl2lG+vqDkVyaOoG3lMZTNiiW2PCte5P2lPbC7m6Bf1tuS411gDHJ9FqVw8ilL3kQ9pHDzhwH1bA==,iv:DPFLuEDtrbWHucI6eQXiSlNRy6tQz+W1meRMnZyXFyo=,tag:CurSS0eg9xUtey3eb9XrGw==,type:str]
    restic_password: ENC[AES256_GCM,data:B+1MpD75PPLEYAsTKdJf0Fl7S8JDq2hQzFRZkErahGjxoZw6LMF2aEjWYdnUiZ7cFSwe58vpr9zc40FB9t9igg==,iv:yS4A6JpINnyiQBHUJ87Bl9W35/VF1jXbI74dxZIyElg=,tag:CWXNg+LA8f6aPuNloM0hCw==,type:str]
    nodes:
        beelink:
            restic_password: ENC[AES256_GCM,data:xT67NJekpRdWkr9RUZiaddLyCYZ0BqvW+c+yOFpptzoxV4eR/h98brxbBqpePLyEJUWQtzt54GV1arDiaehgDA==,iv:kTg9nS0kTu+BX/Op73Wm0U/cTnPZLqR2D9RpHF7jEAI=,tag:1dKlBnpdtmAEyAdUBSXvtw==,type:str]
        rpi3:
            restic_password: ENC[AES256_GCM,data:rkP5bckZec6xSL2xLg2YQSjUV8KX24RlVzC8TfnwweCo7cSeWF73pRrr4y6lKiQ0uiU5eg6JskWKoiTY/qfWRw==,iv:38qXMboPm2Fe4dGBAKg9tzvOvozKT+hltE/zDN5hEkI=,tag:/FEp2Sf6vFXowvTGaomzvQ==,type:str]
        rpi4:
            restic_password: ENC[AES256_GCM,data:RqM9B0ZQ0VA7mc+pSWdNgcZfItHyZgiNZ5RIUkdqaT77DjNIt6gjBfCoftq8gVidvkqMFkT6asSVRiIVvmKKfw==,iv:AyiTn7g3sHneCZO6TALVJMP2yrahbkTmK5KLU2gG3zU=,tag:3kq5q6Gg8gO3HZoUTlrc6g==,type:str]
        vps:
            restic_password: ENC[AES256_GCM,data:6O9P/g6CW6MKmx+teGeJ0BR3jTmYVYapFqnn76Rc+t7ojJSon3slgAtYZ+QurvmygHJjH99OHUYu1t7IH4AuvA==,iv:GkOXP6ie93/sQ2+rPMPs5APYT+YENUqCqjDwv0R8tOU=,tag:gCLpY76PpylHhmCF5oV6ag==,type:str]
gcp:
    billing_account_id: ENC[AES256_GCM,data:C6qYYsL7vUwcXn4ChePYWxiBfrY=,iv:pE0cF8cwdHJjbHoOxg3hmSljM3/6V1YHUtPR3hiJiA0=,tag:IQhOsybfIqsbrkSOFJ2XkA==,type:str]
    headscale_api_key: ENC[AES256_GCM,data:H9OPvTTFeKdI78kaCoRRFdqtRLR+dXqhfEJPQs4Ax7RTA9KXUj5HC3qYN8QPLGfW0zozzd5a3K+J1XyETDKf1an9RT241P9RnazIl+riKJL+J1HH4nF+,iv:a+Uxip6Jye91lt9Ijm8qCSUSe0FAKuJgvC2AM9wVFdM=,tag:12V3xpK4A/FhcwpTOs0qEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QW5SWjFLNWZrSE1NQk5o
            QUZlVnpCWjB1eFl1cXRKd1hrNFBIWWltVTFrClJhSS9Xa3orZ1EreklFWEhoU0tt
            d2ZVaHhRcUhERjNkaHJRbnBNVjY0TTAKLS0tIFNYL2cwQXN0TUNuRTFpeFc1MVli
            N0t0a3FEL0xtNkpDMkZtQmM3TkFwQWMK/ly1qjvll1fNpgSw0X5JqFbCujuCzTXi
            8qz/y6grXpL5ps64dvmgPM13i3JZ5bUmOX3eP4xqGIPc5vrPhxOtBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age166v8efpskctmxxes5lcqpxkj0ny3q74l3v0pswpdpa63wlkqmc8q35fkdw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M09CcGdYd2plUklBaDVR
            cUJjdUVnRXBRWTFuMUloMXE0RjFndEFHNVZ3Cld2QW03Z050QnVhRjFYWEkwK1Nn
            QWRBQ1c0QmVPSWFXVmlJZmlTZmZ5ZHMKLS0tIHB2RHQzOGhDMzBpZ3BWTnk5djJG
            UFJXWkw5U1ZhTyt1TGVvaGNhT05DRncKs8vy0pMjuA8wP4OrG7QyWCmXp38oaGgr
            03hBywer168Jdqe8fi4Mgl1DS79SexdTQxuvvzop/nace8ihJQ7+Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wpqxa7vqkr6watypd6zlw7kspz506kq2kvluxnluhz72mgtaga3qlg84cv
    lastmodified: "2026-10-04T02:47:45Z"
    mac: ENC[AES256_GCM,data:jr60jF7UuPCZU2uBvccou3BcitisMuat6HWsbuyMIs9Ydi2COP0EPF2x8LUtnkrXjcwrE4jq15cPyapMRCfJnHYV+2hy6bpyAvGmCQMeerkFLCrUXXd0op0ixo1Dro96xZ3B3vQd5xtURg4GGEVM6yYAD/pS7XPyfjHiDeiHalQ=,iv:iyZv4aJgEu7pjJnMngwLDTo16S85Mva9Ve+7ZnkTj/8=,tag:Cs5VAAAAqjUDhSocP13p1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
