webhooks:
    slack: ENC[AES256_GCM,data:nO0/cFvcgzVOz2jcdw6qdAIqsziZnIrfy27uQmIoIIk+peYgRIJinc7omXKaAeKkNeCRAX+iKkKfr20oZArOxBNjbqae9gzNeXVjLHzg/7xr,iv:2EzSDG3HEHPiWlcVUgDkwUWO7xTA7SIsgHFMbkdDiM8=,tag:TfDiihpTp1BqFXCXbterhA==,type:str]
dockerhub:
    username: ENC[AES256_GCM,data:V/7Uq2litDvwZKs=,iv:+SQESef0Osvhsb8NNa9kvi8FFxxQ1MehLF0IccA3IqY=,tag:Vb72M8awEkA7OBKZXxgoBQ==,type:str]
    token: ENC[AES256_GCM,data:w5kHkb/SpauOvWKBGI+F3NX5nhOXvQuy7SI+bJC7r4heq2qW,iv:XV+/QBQwSItOoY9faPqWSddnwzJMFv/Mvg2gxj1TIxQ=,tag:RApHJ4Chb9rKDw/+neSK0g==,type:str]
hetzner:
    api_key: ENC[AES256_GCM,data:h8dOPTaz7krN2pWjGMfcSds5R85X01Oii4xhA1rjOGtGzDqVdoK6dwvXHucHvCk3VKZ+I4yZP7pG0DJVt/4fSQ==,iv:n8Diqprq91dqy660PaLfa9zM1yRYpOhTLqCfZGaRmHM=,tag:e2y2sTfNownUl6KylgHLcQ==,type:str]
cloudflare:
    api_email: ENC[AES256_GCM,data:Yy3ET/q9gCkGZW+hOmxMwnYpe2ke,iv:U2Z7qUZ4X9Im96lvjFB32zuFHk5k7wS7UVA2dl0k7Rw=,tag:TY72L9qF4jh+nn7wwVRp0w==,type:str]
    api_token: ENC[AES256_GCM,data:ys/E+P6DLkXyzkguZkwH+y99EITQa6zpf7ZNQa8LQCNHFDg6vt+vSMSIK0Kzju+QEpGgv00=,iv:0u8uSwSAOFAmtsPM6XWr2KxFepsqV668Z1PPl4yDHJY=,tag:stia2FghUXE8FgS8MRnj1Q==,type:str]
    tunnel_token: ENC[AES256_GCM,data:IeijZaNn0wV3m2ZhBgNoS/C+HCyOlyeeBlCDui+ev8GltJJUzM3TM7H9r+0K7uIKdheRpkkOlly4kUkAMkDMAN38aMFN620ILmCAotYDMXjkcLnZft57znDbbtPT9d72/ufTN2l22fLAANBPa+TEpkpfWJZi7co77eWPp+jYzD7bAbKI/oKUV1XGI6MX+UkbGEvZTEZ3ggM48kyeGF27vlwxoHilXIP202z6LOy7g2XAE46ZI09+Tw==,iv:E1G7UPINEJXB2Y+DEnxEmdSN6TPuUeC+N1T6t20pElI=,tag:I5o/eKVMm/eDR6PqmEH+ww==,type:str]
    r2_admin_token: ENC[AES256_GCM,data:fRj2Y1itaMaYbWoC5E7PhFRcWumcjszUSXQFH3w+FqfUXbPsh9yd7UbgO6tFFxbh3/EEeYU=,iv:ZoQ80XU1oc7gLjQTvz20Bxrd1wH7ACuZZjUyWzdG1AY=,tag:H5iCtjex8XfDN4Q27cDFiw==,type:str]
    r2_token_minter: ENC[AES256_GCM,data:AwRfZsmBtX6pCL3Gf1IgVQEnp0x9ZRydidiahSqnH8lfTBMs4QtVQO1O1VL/HgMRuWngCYM=,iv:x2Q9MpXlq5QHSnhrLH8k/Dq7ToBJxmv6lo4TJtAHy3U=,tag:sBfSBsE8nMotExg/P/UqQw==,type:str]
apps:
    platform:
        api:
            email: {}
            zoho:
                client:
                    id: ENC[AES256_GCM,data:0mEF2TewDoH+rJMp21e18EO4zb1t++p8FgSkV0kUycqX/DI=,iv:2Zv59ZjSTBMwKguxkPL6h7FvxcapMMSLvDlluhBDFmw=,tag:irwhJsKJhYIwNzuS4TdT+A==,type:str]
                    secret: ENC[AES256_GCM,data:UD6f1jE0OEQrdXRfKGM5lXYmH2CPewGqyI5DutMrcldXmOGga4CGjVLZ,iv:lN2Ys3Ho58NYgo5rhur1BJnVTk0s00lf/87hkfX3MUk=,tag:0/U3mxa1y5RhWpnt8GEjxw==,type:str]
            beehiiv:
                api_key: ENC[AES256_GCM,data:8E0dG26Jk5hUKtNDh1fZmk+s3ATOB7HAWuavN+pNnslUIWjLq9/DeJDVFzthWhhCxLhMe4llrP5QW/Xdf4ciQA==,iv:neSs1QZoYDdQcxI7nxPbIFUGZRqemcFI9iY+HeEHjFU=,tag:xoqkXEw5hoOGgnqpzf/KDg==,type:str]
            beehiiv_api_key: ENC[AES256_GCM,data:VK2LfQrUQDYWQKBMU2wUn7wn1u5mvXDVDJJvMFO/DadIK/biMmyJjof4CG+WXsUWzP2zt0RKvj7aT2N/GQ/BxQ==,iv:d8GoiCghvBXYm2bgNHaxmAP05JZzEl/CtDX7DE28gHI=,tag:clxKuhNcd4FGRZMMyBRMQQ==,type:str]
            zoho_client_id: ENC[AES256_GCM,data:u3uOwtAF8WhvGA10nKxDwadQ03ZlOi2XiJzdq/Low0r6dHE=,iv:SG+FOiY/jACnLX9tewogdhWMulX3fFyEzC4KKXrl48k=,tag:PpAPkvN+KuwP1KyDTnQPhw==,type:str]
            zoho_client_secret: ENC[AES256_GCM,data:xs+nlb8sOILVQmp/Ocr1l6aCFIdLQ4KUGllK/eeJyl4m7GSiIhUg3Fos,iv:I4cOfkii0Ri2GX55gFVmG9YteXsTaxXWrKuVeVgM3Rg=,tag:mGDwZFnjqN+ToLmPpUgsVg==,type:str]
    services:
        automation:
            github_runner:
                token: ENC[AES256_GCM,data:IeihsAIbXCFEoDFKJ6fKqEaZquw3FGqgJ+t57S5vRYGqHeBKgTKagHU5rPpyX+J2owFlvXwn3OPHY/Ey+65zR8LJ/ibEtZesymN2jeRlCCuecpwzW0FeMEMQQ/9L,iv:p2BwhLoAYw4sGl7SmZiNCYVhg2zP4gKMH8vdELjsL1w=,tag:KzvZMK5PNxi9q98kWJPgZA==,type:str]
            apprise:
                telegram:
                    bot_token: ENC[AES256_GCM,data:42x2G1DJlGfZERY40CYXyT3ceYawBGFAOcgcYT/OfZiYHvvyOYqsI7ZjXMyl/g==,iv:AMSyIBVo5WamqTOdDT+DndI91r4aUamcx/ua17jimFo=,tag:mm81afiTb5yrK32gXOV1AA==,type:str]
            dev_node:
                github_token: ENC[AES256_GCM,data:VQpRrKydJQjwcECX/u3pWnjIGXi8TDDG0QJtV3uLNPwVbUwN1DsfC5A2XYuHP28nQ0OXpJ1qsRJy1PTECNuqTknpHPn3Ip5r9v6suVHO1dwkn6b/yYYEaa6vZWuh,iv://YRgydkiU84neaawmLOR6EReQGquUlXCbonJiSTkNI=,tag:R0z6FJnljvliHqy3vxNLvA==,type:str]
            notify:
                fleet_webhook_secret: ENC[AES256_GCM,data:IQnDjvlvONIuHmFr8oFdWzlg/TTcHBJanByLINL7TNA+FLuEXRcShKO31dGlHdV6Q7h9RCLxhXteQ2wleWsqatp8fE4anZnjkXe8DcTqBioRtRneLKE=,iv:65ZEeNZ8TAQg8mgtbEFtC6RTMSGs05m8h7UwbqI0hwI=,tag:O57F4+PKKWk2rLgtNkaxyA==,type:str]
        security:
            authelia:
                oidc_client_secret_argocd: ENC[AES256_GCM,data:akdwrtAQjHkHzjHfihxzc2PzZb8fe7IMn6Oi7c57dmOvOEZjCcilZojWk/Ybpp8711J/KDLktBrLGsBshsx80xg+I5ec0kOb1lIHpjiHT31e0GjSh2Y=,iv:fqsyY44mJ+q/FRsgHAdL0EHvzuMpt6MrimmMazfyXhA=,tag:QnokIexDRls+V+myUPUYoQ==,type:str]
                oidc_client_secret_argocd_hash: ENC[AES256_GCM,data:UUnrxviEg5wKt4kEzIL6AaaBmDlkXqnF13QzF2fi+aNmFPHATMGCEe9ZaVRrwjY0uNtNqkXtdtGiB56EPYHePqCEvf+237H5Od10YzvtXa+CRHyOeRNYM90P76fFZGmh2Q==,iv:7VD63g1wZudhURX9SG79erGItbyYCJsDmCP5vKIG5Nw=,tag:I3TxXyPdFDtzZ/5BLqofkg==,type:str]
        observability:
            uptime_kuma:
                api_key: ENC[AES256_GCM,data:4afWsIs7FKhr5CP+gNy6Rapf/d6NLYdpMkJ8ZL95SOBjQ9SKRJ9PbWOkcsE=,iv:VLbr9pmNyGoGknLUqR3DPp6rQpG2p9a3U9E4b6PWfCA=,tag:PrLpiITU2N+NUC+L4xYpRg==,type:str]
                admin_password: ENC[AES256_GCM,data:q0AnjXovzlx5PNVIpqqw,iv:ClOf0JOxS1k/9WQO+XsptASd4iQBNR2SQzRs7F5d5rk=,tag:xRw4F5DVocxOzO6QW2+pMg==,type:str]
                admin_user: ENC[AES256_GCM,data:9NACwQ==,iv:lIBHv18TPbydsljYpCJ7odj7TOYAFMrsvUS43LYq8pU=,tag:wEl6fFgSNjIgFOEOOxoO0w==,type:str]
                push_tokens:
                    ops_backup_node_beelink: ENC[AES256_GCM,data:ltYEo8nk/8Z+jOgjUsVow+/AZenFFNEcJv2SApu4CFfkLuJ0bzOuTkGGWQ==,iv:2bQPLcCzPRX9bQSK8F54rLpSUwbwfDWYa2/yfZCal1M=,tag:cIe/QqnVTYqx/5Ppr8mj9g==,type:str]
                    ops_backup_node_rpi3: ENC[AES256_GCM,data:jCHk+eBWgHyJE7T4MmlA7dOpBovZ1kW3Ch0HAuZWGqJLJNKvCRqBC/YD1g==,iv:rj19UARxPsfHqph4WLL1J88C+2VpByq1qVUyrTAJWw8=,tag:ZUpt0eH94voxsz4Zp6bMHg==,type:str]
                    ops_backup_node_rpi4: ENC[AES256_GCM,data:T9O2lUaLdYfVzag92kNvKDm3gvEbXp8SVPCNCRsV4K1DmlWiolKjM2fZBA==,iv:/QmMQSovy3+QP1hY4e+8Fz7p/6zRJj2XZPZn1Qla9HU=,tag:9oUXw1wfHK2CAchW1YpGsA==,type:str]
                    ops_backup_node_vps: ENC[AES256_GCM,data:QIoKKIbx2tkjASIcCYiEi6MRhcwiOt/dN/4mm5d7qin8igESYUnbQaKZpA==,iv:sJAM5GoHQV8LvFH5koL+j7nTwztcIMKdSGo5Kc5ZYYY=,tag:XnAkYjcMGPq3ZJWX416uDA==,type:str]
        dashboard:
            homepage:
                cloudflare_token: ENC[AES256_GCM,data:sSImon6atuDLLJ00A6keOqq+tsJEvghwq7qE0dWU7ffdNzSmio9k2GOKqxsIWkQidjVw+j0=,iv:vZCzxzk/eAPNbFbBTTLEuqgfVGwgMkLJywdkgs1bBPQ=,tag:qef5iMebG1RHvq8cgEjd3A==,type:str]
                github_token: ENC[AES256_GCM,data:oZXdbJ0xfCADqNhl2XnqtDmbIJPmC8UVROpJZicMkC/a9Q+g8f/hZw==,iv:fQ+NxGVfpEwtenSFMje4SNZUSMrv7ksSOxMW+3+PHHo=,tag:7vjOjObXQxwdL9VO7KigTA==,type:str]
                uptimekuma_key: ENC[AES256_GCM,data:Qwvv2kI0VYFESJRHPOB2GNx7dzRCDhu6bcCmW8QzV5T1p307321fxiqY800=,iv:HOqjkqXEDITSasvxN6BBgDjHtzNPBUgkabsHP3pTHko=,tag:I95Gla2a6jw8aiz7EMlgow==,type:str]
    testing: {}
aws:
    access_key_id: ENC[AES256_GCM,data:BapVLMQngsBj0PYZiB8cUvtK6X4=,iv:M5fRzPhqMJDwjNBSPkMPICYvLeM0al4F14SrW38zPnI=,tag:DeYwyexWAeb7lA2RLeRM+A==,type:str]
    secret_access_key: ENC[AES256_GCM,data:jqqAwKbOsrFUYnYjOLcDj5LHL3DldfSd5NHcoRsNyGg4HdGTLkRZWA==,iv:4i3jJHu57gdbwES/3lsjFP96VySKddAe2iE9whMG7V0=,tag:s8ocYEUAXy4bsJpPQw9/9Q==,type:str]
argocd:
    admin_password: ENC[AES256_GCM,data:eQGBWl2edyInqRFE90oX,iv:reNPhJ46zjG8OTllqRcDgNF6ZKt/6xJh1n0ju3bUXXY=,tag:DCIyxcYQepg4BRc7UJm5UA==,type:str]
    admin_password_hash: ENC[AES256_GCM,data:tN2rB6nUh46plYXgGA5FkSj4rg4HUr+sBol/gJYVZwZhvH2q+NUgxwnh8JlXSJCpapVCKQF4KMctmNPe,iv:9bptPQBbrMx7hj5GkUoQABef0CF8Acj09B0+vEmG2L0=,tag:DX95q/4tCElyxEbiPkNOZw==,type:str]
    slack_webhook_url: ENC[AES256_GCM,data:/0oSZ5XhUlP9/tVcZ7bNWqCjnziystgFZilejdY+NqXcpNuQLPjChz2fsnqi/35FV9mS2ngeHe9jsB9eThyewS4sx1vy+VFTRTqEkF3PXR4B,iv:a8RH8yAwBJm/eQN0tK2nj1dZMCrdTO/po/CeYG6mrK8=,tag:2DtYW6i7msSmn1tRV9pS6Q==,type:str]
    github_webhook_secret: ENC[AES256_GCM,data:JxLq3d6KNIv27xOTF6uEX/B1TrgBRibJ2jVeSOKFjdG/8dC7P26Cx23ajPvUsYVvThvrnAvpnZAi2Sb1Wrz+8Q==,iv:QiWxWnr8r49EQm78dXSPNBHCVN4EkRt4SZGTrysfsAw=,tag:eE79oecm7/cpJ0Es8LHJnQ==,type:str]
infra:
    smtp:
        user: ENC[AES256_GCM,data:juY1rPZns393lMyNW7zBC5usNIk8,iv:8PJPB+bJ5DjkXtcgOikdcPpCWLU7TKIpU2Gfo4nbJ9w=,tag:Fa1+5nF8Az664QGdu6msGA==,type:str]
        pass: ENC[AES256_GCM,data:YjB5u0UvzgvOCjfzwUFSyUoDuQ==,iv:pISudm99ntgui3j49qaweF+aoYsETxhVQIRGrBtkL2Y=,tag:LEIjG8DsIidFOIcZL3WQzw==,type:str]
backup:
    r2:
        access_key_id: ENC[AES256_GCM,data:06wcK4fHtwdd135qPesF1NpmsXMliA5z+IqoGVfNrSU=,iv:9zEoezRhwiFRvuKzdFSOxXpmaSNX2z8OL8vGv2IZLOM=,tag:qZbDoBuFpo88mfT5FSo3rA==,type:str]
        secret_access_key: ENC[AES256_GCM,data:8D4nAnPgOywSG+7zsrUZfN6MlRG1bMmIUKYMpKg+jOKs8hhUE7kWfAsPzo10lbsT48HJAWsx0BR9i2aIhGd80w==,iv:cbTpTQjw9Fat68fbvBhl2FTtBu12J5Mjx32kXs0OcQ0=,tag:CJmRIK1Sn3tMk+/K0Jz3ow==,type:str]
        readonly_access_key_id: ENC[AES256_GCM,data:X8rIJIgmpsk808ZSHW7nStd6Qg+aHOMi9sbtvkFlzpc=,iv:YF8AQHErUfMcS0GFD0GeNIUBIzOHKlS+HE02vABijAY=,tag:uzQqlVtnV4MQ5SZfJLL2ig==,type:str]
        readonly_secret_access_key: ENC[AES256_GCM,data:V5eSkA69rH3bnr5VWkRovrFgKObVoaXjtwe47jBqjgIZnSAoN/IjO5q3Pkiqi6iH2zf6SMTgz07K+wjys/u7SQ==,iv:5pjS7HZ+JenUWHqJcGffqlmTNnvpQ7kjxGoOwcnWWM4=,tag:XOV3BxS+wZnpt58UrGdzFA==,type:str]
        watcher:
            access_key_id: ENC[AES256_GCM,data:KSB5/Rqx66GkB/7yLhzJyDzV4YqpXTZQhFEjM/IILek=,iv:nAribDCoQsj/zDV9FVs6ps6vNomEV3d6pv7meLBVLVk=,tag:YV4a0Cc3k3Od2VI+qi2smQ==,type:str]
            secret_access_key: ENC[AES256_GCM,data:jvLddcfVDuaWsZjSSRPdtvbWvhGdGX3dDkXr2te6WJ5yWGeAJpKXvZOj0WGl583Mollx5lThJlGmvWSjLa7/vw==,iv:58reCJrC52KlC3jtGmc/lFFTR1j80E9yXnhnpRA6PhQ=,tag:S5caFjj/AgtUqtR8w4fT+A==,type:str]
    restic_password: ENC[AES256_GCM,data:hLL3Z7goepUoSwmRGDfJ/fJ0NM21Kv3fh94mfH1BG4LruKE7JuprQ0nO3pB0wxIXgHjD7mjeu5LDX5439yo7qw==,iv:T8RbEkOQCPIDAdn25rKArr4Qr/8VdFOHeVKuglml9s0=,tag:CPenPavveYQrmgEcmQeyAQ==,type:str]
    nodes:
        beelink:
            restic_password: ENC[AES256_GCM,data:T/FIPKkhXw57H9EZCTSaocdk3W9Ong2kodLUFMDqlX/ss1ymKOH3B/+bAg6wXMsmBRoRJPYaC3Ywj1IEaTEpqA==,iv:sUKQptqT7gF8AQzw4UGP1dHTxQlZYfw0KSyRHgeaA6I=,tag:x3wig8n8qh4Ek5fWneh/pg==,type:str]
        rpi3:
            restic_password: ENC[AES256_GCM,data:0YjlQKN2qqJI7b6etVOxxzjUCb+i/iEigbC54qYKaD+PSPpaRBhgPTGnoE5IfNNQht4iw6nOreDqPHxKJ6PHtQ==,iv:tPzUMDIU5lBiX+BMSFAD/vPhqHZIoA40kSl9wTQh7CA=,tag:TWpfwd9E/dym2tGGUKJeiA==,type:str]
        rpi4:
            restic_password: ENC[AES256_GCM,data:UpBO20N8MlkYeK/fBU4SSR310SoLRF3KVujknG9UtVO0LZEM+fqv76nuTtl9dYowTmNvEPnTJZX/2VZEPBwUuw==,iv:2GIXPZitqUPmfhG3KNw39vdUGTtUU6nxAefYnQnTWHc=,tag:z8Sn6dUaE1dNG3rn81wiWQ==,type:str]
        vps:
            restic_password: ENC[AES256_GCM,data:VPod1g+jwYSUrUSGCu39RYEwE4Bwh81JrC0XZnPd3ML6TL1HBwC5bMt+Ud3HXxc357qOazLd3p0qwYssEB3wVw==,iv:X7FD/uNq6JQN8gk84G02zg0LPFAL1czB0mljzlt+030=,tag:jhlX70EqfQtiGUFeDuSP1w==,type:str]
gcp:
    billing_account_id: ENC[AES256_GCM,data:ciJLhGhIQ/sHr08UdvCdEIWTPZM=,iv:f/q7rTcnCQwnQeFlhIEihEYucCUXjz81UvtqdcFo/x8=,tag:k/ulTMMqcMIZmqyhFhccTQ==,type:str]
    headscale_api_key: ENC[AES256_GCM,data:lYpccer1ggJB1xYrW0XHZr1kF5n+tK7GW4ms5/82iG+2r/u8JAb/acAnhi9upaaO8Vi7j74wsrwi0b4/ByjN4ZBMLmi+0Rp46tUaJQisFysu3L8q0FgR,iv:wPj6O1LoSvjTBDWKqQILDGfKgsJmSNwmJcpU2sU16sQ=,tag:TUDC+EP6sv2rOXzCS7rj0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNUdEZjY0S1NXSFVPRUlK
            VDdVQkZsZklUcGlkVFB5ZHlRV1JLUXBqTm5jCkF4STdCL3pqcDRsam9heUQ3bnBH
            SUpGYnVsdklPbU9jb05TQ1g2cWJYbUUKLS0tIERBMDFPU0REME5Hcy9rNEpjRitx
            Z3IrUUpJeDNqRDRRelhOLzhoOGVrN0EKMWlD9wZO6BmvnzyABneiWMXEXO3mZvqW
            QLhR1eJNq0Iolu+/UGbrRjiD8Mi64628zm8L29RxR1jK4rId1gqi7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age166v8efpskctmxxes5lcqpxkj0ny3q74l3v0pswpdpa63wlkqmc8q35fkdw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubFJyaFNxYk90RmVhZUI5
            aDlaMU52eUtKMDMzTFEzOXBRYnJXWHJ0UkRFCm9GL29JNjdHR1FBUDZVZGQxTmVR
            djRWUytsTzVnUXkzM21XS1lXWEV0TUkKLS0tIGF6QUZlK2RaMTM0S001bUVJbmRv
            dVZncGQ5czJGNklqS1ZHOEd2NWo5b2cKnZA0xorJUKiH7A77UNqZRsX7lZLEkpGa
            KGAxS/xxDNWkTL40bGg8UbAiWsT3EIrOsyqRS/2o/mY7kfimOFUCWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wpqxa7vqkr6watypd6zlw7kspz506kq2kvluxnluhz72mgtaga3qlg84cv
    lastmodified: "2026-10-07T07:08:18Z"
    mac: ENC[AES256_GCM,data:SGjRBpcRGIyPitvqTGzMdPW03M2vWG7kAJxyGE5joe31VW1V3mjl7G6vtaDZnM3gRQi7cEOdubUaRh3LsxhrqPNnDulVwevrGQzHrJ2a2pNGDmjAgc3OlArhaOC52RO/25oPZAmaf87h8BH7FjlNjLKoJHQRw81nExML6aiLNCk=,iv:exmHz6MlX3OeyyrU+LA4QPztsvoEYCavT1B6izrzn6g=,tag:2C33iOtZqEk6QA0Hrj5igQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
