basic_auth:
    user: ENC[AES256_GCM,data:WDzv56Q=,iv:2PZrBdzMUBnZEzuDoONBQgveXvgdlN7wewTwlaRQJXA=,tag:1Jdzr/FgcfGvLqYa0JQY0g==,type:str]
    password: ENC[AES256_GCM,data:6k8Y7yO5y9dh,iv:lB+2zGuFMjf0Twhvtln6HEQAW+xbxnvP1Ua8OXcH/44=,tag:+yBqDRzxE/DbYUgCYi5KZA==,type:str]
    credentials: ENC[AES256_GCM,data:G8RriX8JaIKBwf2hiqvCrHWo2aIBXkz8wreMtzfM9GgweqGI3Wz8nKYIMQ==,iv:kkVlAIP28JLByDVJ2X9mWj7S2rmKN9wpCuD3rrPccwE=,tag:Xd1g+j2HoNIIyWuU382msQ==,type:str]
apps:
    services:
        data:
            minio:
                root_user: ENC[AES256_GCM,data:uKAZ5z4=,iv:F57VYHV8wMG4QIjy003Cla267TTvCScKunoo0+rkCO8=,tag:LLuH2Ft5ufuvJHd2tO3WrQ==,type:str]
                root_password: ENC[AES256_GCM,data:VBQQJWXjrfye,iv:udvScU7qfjXPmBqq2Zgn/ksQh8RneU5VEwZeBFTSu+c=,tag:RTgXOICGkO+zb8wTygZkJA==,type:str]
                oidc_client_secret: ENC[AES256_GCM,data:VyhhWpcKrJz0YgPRfUAl41/16wFMXLnYP2CskjR7+ktsC0359LOU/TTXmtCgaIXndWT/jV8DKGB0dGALxUZtwLZjNyLQgvLd9YvLXidu9RFEV3UWYwU=,iv:bFWoi6BvPjgvHJIb9TFP49KxpWMH0TPZIb8VnBP31vY=,tag:ZhdtSpvt2IQzd2lJ8xCFWA==,type:str]
        observability:
            grafana:
                admin_user: ENC[AES256_GCM,data:MSb/q4Q=,iv:LXBUoO/X6K5pnso3cdBBUY7cAG3ZeVA4i7OFyCdiZVk=,tag:cpKEfRhPClqpNFHOlUQo+Q==,type:str]
                admin_password: ENC[AES256_GCM,data:MV4zqbXm6zYT,iv:wo03Ntt0j5xvB2bfzYsIjfaH1xKdVxthsXyvIXH6MAw=,tag:yVLxRd7tL28GF8CzZQGDeg==,type:str]
        security:
            crowdsec:
                bouncer_api_key: ENC[AES256_GCM,data:BThJd6QBu+UdU+wSfPPgvWjKkIsxQCwTLclJ2eJfZn9XVM8NH/ONG1tiOw==,iv:20h6GvIENQVpJQ8Bo7HM1scUu0zgnaza47eFca5Mo/0=,tag:PLPFvMdK1eleG+4Cw3eWYA==,type:str]
            authelia:
                users_admin_password_hash: ENC[AES256_GCM,data:IL08C5TEtTn9x3e0PvhxoCuljRzPXoT1dyDwM/qzQuKZA4o+5m41xlFSFxZzJmiLUMP3DYBtY7bTi16PenK5EPHgWrDQyZ9HXxFcKJGxuo6PyOPexuNPDkWR/OF2O31S8w==,iv:2I1PMPh0VX8W4HuoPbwFo8nbS4V9VFuOCjp1Yk0xJQI=,tag:M+LFBKoj2xevuBugdlW8Sg==,type:str]
                oidc_hmac_secret: ENC[AES256_GCM,data:mRguoLbCqQWk9mYaAtPUTkaK1cLfmz7mRpSoFBGNJhTFFCvTl9hclyzjdiNdEVmjh7Ap4fr0nVINWoM5UFKfAlGI4neg29JztuH74Gb6pUV7WkNDuKk=,iv:FplZrZpliHjKI54WrOzgyhMFUMu3+blnQ8HWVYnCnag=,tag:7b8YLfCUOr2saWAn1y/pEg==,type:str]
                session_secret: ENC[AES256_GCM,data:3DXzcwaiwmjcHF3kAcTTuWCAVcWWuXue1nLa5zNJ73VjmmjcnYDwKz2n7bc2M5OB0lChGKLzLeKPwvymK3tKY9ArSOnPTNaWqa3QfPIFWW/mTt6gZ80=,iv:9GQB94UYfj7+5KJrZylo6YzYNOWjR5iUk3xSGXBps/A=,tag:WpXtdZib0oV29ju/JMrD1w==,type:str]
                storage_encryption_key: ENC[AES256_GCM,data:QJ1EdzinwOufugPod4T8D/lAornAryZylEXpKMofVrNjMN5rcfVSPfeCSbaaYufMT34N9D9GjOxmS26RRb7ogedGyZSjqkviATj0A6brxdVqYXhFRPc=,iv:EN+T0P54eNzvh9Rt/0kUj3wGBYNY0wFjeBsy6BI65RU=,tag:+bkkc9dmFJkXu5NQ4U+CJw==,type:str]
                jwt_secret_reset_password: ENC[AES256_GCM,data:9shGSN834N0jnqZhm9xYxPCP+gLUzoVf1DScBvhaR/AmDKTBy8XBkxI1gYWMnImUf51Xe+RczddsQkVqBxCm+80TP/XQJx4AuF529VLmV/SYO9Dz14o=,iv:xGzaKHxhBBUjqPEnWHuVgi5sGfWDbFmtuS5WfckjNrM=,tag:iphEenzLYQaCTaObGOklww==,type:str]
                oidc_client_secret: ENC[AES256_GCM,data:7GugvLcNiExfAf91/ibPOeNbWeI9CNBZtAGxtI1tVDDIbbUEAmSBKh1TXCqwYE+v232Mx7YcDCn7L9WKedA0OkKdmmzh6Hih3af0WpyhIvShA1QRhh4=,iv:HbwK27FWCU8cJ+/JEFlr5f4kFFTGQRCTAosNsOcfB4o=,tag:4ZDoKNj0D8zcaBR0gTSrhg==,type:str]
                oidc_client_secret_hash: ENC[AES256_GCM,data:QOeq5KUveN05/y+/tRTkrQ+Z2sfzr+d9P7/raTmf1pt/QeaWhEYRy03UVaCiA2d/jN/j8ueh2CQG+GlpuRYUHt2p0RDbFUzh5U1fNAzwlMyHBpwwjMk8RN+erBikRMppEg==,iv:65r9cbGIk4TO/Nbc69AEcReK2JdYNU2TTZlUMic67ew=,tag:HwOX7CHTpIiPtmvHQQvGjQ==,type:str]
                oidc_client_secret_grafana: ENC[AES256_GCM,data:VpWshcZNr5SE9pdXZUVqK3SEkvOwcFOQ9vwwnG1gzbmK+iIIY4FVN8E7erKhf63N8eUcshbg1ogQKQc65N8jNrNkkV54nh6ldcH4CobdaI4R0iZ+lCw=,iv:ZJWezfkMfVyHTpnMs2M3SnheBgk+cJFDZy6JaybLUVw=,tag:pBQqPS+ufY+J+qr8BVcmYA==,type:str]
                oidc_client_secret_grafana_hash: ENC[AES256_GCM,data:TZJSdUD7BxdUUhCv0ecTzbXUmXz/2COVaUzT3IFOOVy6fHByE8y0mNLuE5eDe9Cc4xQBKvhJLgepO4I5zBwXzWih036/TBzUSwiruEH5+SZdxpvj8z3I1CZwgw8KReSqPg==,iv:CqyOc+zpidywKnABdl4HW4LpeUkS17vmlEQvvlB3Eos=,tag:gWtmDUk7ee0IReHsYMS3Tw==,type:str]
                oidc_client_secret_minio_hash: ENC[AES256_GCM,data:0nl9Ed49htMFQj9LxvhucDwoqgUDKCwoLl5kiVkclM6q7N4s2sFtPeWWVO77+Ke8xC6dDCc3PQkvy0Qc1uLoIpAt+CRoEPGXxpYb5rSmBYf80T4awLLFDMIRmvNyecgIhA==,iv:sq85uzk4Mcb+fouKokaFfzXN+Vjpu8xCG5YVVcnge+4=,tag:/grPAw+57zr9kvFRdi8xWQ==,type:str]
        automation:
            github_runner:
                token: ENC[AES256_GCM,data:rBX8I7CDIDoKQT+GuU90twECBHOrEwvKCZ82joAbD9nV0LdAmE/DSQ==,iv:WorOhZNnAQi2KaM/2sC0sV6K37P9Ok5qR/yzfV95I7Q=,tag:bd2kFwMuUp1j+riuVhQQeQ==,type:str]
    platform:
        api:
            email:
                user: ENC[AES256_GCM,data:4h1pNEFBbRTrJMQgX4IiAbqTnyVv,iv:FF0g9tYjXVGnC77txM1n3jeR3MhySB0P0cyBfKV29Bk=,tag:lZ5Jr/j/KsdsVOFS7g9EZw==,type:str]
                from: ENC[AES256_GCM,data:dsZCazJ/XmHfxSg=,iv:r1fBnw8e+vDDrBdL4jeLB/7gUwkOXgHCNjw8ln7rohE=,tag:AtNqmT3pPlAqiVzas7MqJg==,type:str]
                pass: ENC[AES256_GCM,data:+7aWI1365DiiVISmAU5FrKAqMQ==,iv:5Gr05+IF2lE3fdXwPKcDiDrQ8cK5Eq83t9aPVShlS1s=,tag:4WSaaxcwykldIgRdzGfNnw==,type:str]
            zoho:
                client:
                    id: ENC[AES256_GCM,data:McrFhptFVyc3BiE8E6X57o0/dKYOrf96YUm64/HjGrEyouI=,iv:KTvhwlZmsT0QZjKiVjp/CQ6ceWBswBCFObR7JvNCyJk=,tag:/na6NPlMV7+GNDyl0mtBDA==,type:str]
                    secret: ENC[AES256_GCM,data:TtqgdvMtm2ek5L0Lf7vf5PP979ikWpVATEhgBFYdwi/+6nkhUwI/mc4I,iv:MUYtn32LaEMt1aGRF2Wbt7kOCcD+xaW+sDmpWwYZnBw=,tag:5GF3y4yG6j371IfXfZthSg==,type:str]
            beehiiv:
                api_key: ENC[AES256_GCM,data:Q7tQuHR0CPWIJdvihhGlGD9n497uutvSEnaggfiDNa6fnKbfoww6SxG7hdKG2tamUfjJ/dqx37851qWrQ5cNYA==,iv:QAkssS9O/TaOAwSEKMzVn6V98FQp50Yvr+YwhlKNF4Q=,tag:tuEH/lBDZlxdhea2u3pYsQ==,type:str]
                pub_id: ENC[AES256_GCM,data:HJBwATbqDWaFJK6NQKcfvye1PGH8xr1JcTK17zfCcAIYIN7+9LXymA==,iv:mSBmfFjavkwLgGp+APtUrzMGXImPaNwOgaXiLqB945Y=,tag:qzzCSok7ZxqnXhPOM/wjbw==,type:str]
dockerhub:
    username: ENC[AES256_GCM,data:R46MOmZZFN5p+wo=,iv:boQUQDBXkfHNXN9HQHpTL4TSlzM6hr3ykHQA5GOcSWY=,tag:23NY9X0ZX3x7Fddl9203ag==,type:str]
    token: ENC[AES256_GCM,data:9kJCzdtDMbEW51rh1wmJqp3BhBFWnYLWQV3sxjHmleF4RHWd,iv:hngCjrUAlAnG8NVYF5bRxHIOkl2xHGpcm9MFZnYdYd4=,tag:BZPjMeX+TU3bHl8itIaE0Q==,type:str]
hetzner:
    api_key: ENC[AES256_GCM,data:YCWdBFYYaKFfGQPCDANxU2Q+U0hxQKwlV4JJcOfJ89w=,iv:oggfro/iacL3k7aGJjd/9e7/2I0vsuXC++zyOyaDENI=,tag:K4M6ZJdLmwk07qVEuU7IAA==,type:str]
cloudflare:
    api_email: ENC[AES256_GCM,data:gAyJugvnWFVAVLYsGN4KRt1UNGNL,iv:zegYIjasjJfqi44EM3Me4QwqwRKlCEyhW+oZJwgm2V8=,tag:g+bXqwyAHgwl619tbgEuMQ==,type:str]
    api_token: ENC[AES256_GCM,data:xowTqwbc3gbTkv9Z3GvWZ+0lqe1XErIOQU7I3Y5hgBop0oXKUhQ8zA==,iv:Fc0mvl46t8GKxRjuR0ltRje8ZWE0N9JooJoVk95AAfU=,tag:3daE7VLPteVlx7tA5jw1kQ==,type:str]
    tunnel_token: ENC[AES256_GCM,data:knDIHuxxSTd79pfbXftikoPiYhZmuqGfbQ/RV1IXa6wDSwUKSIXA/6XhkSLyAXH6uSzkmPglt1mUcSdz35UfcFUfzuB2Tj2kjBGt58nAab4vF7oI1Kd2IVJ+6b+jlKcTCqS871WLv8eJ2t7LnLejYYMQzpZ9Mn1zhlGh6zb4n+5h7X+NbWDEkpHGAxUhkopIwUb+ThXqA6gJAVU3ntg9g/k00Fa0qz81zc0vmgbn0SsHjY1w+2c2MA==,iv:R+64gCK5ZHJe1EEvOTvCywlIdzI2y1wh/0rFcH5SDDs=,tag:jGoW0paFYapjbPhq/p5bXw==,type:str]
webhooks:
    slack: ENC[AES256_GCM,data:FkJcvP+j6kJFeg6ZNM9ROxuceUKrGsXtPlAve/39G7SVAcsd7v20u8iByrCsXjhCg0SjzScwj3dzTgy1uFWoU5Oomtsl95XxffDsW66ZpBXg,iv:ONNMrf7VY2oqeiOM3ZZHqImjvBA0JtOX/CMbbGAvBsI=,tag:E0Zj7EDyAEYclcxInnE3Ag==,type:str]
sops:
    age:
        - recipient: age166v8efpskctmxxes5lcqpxkj0ny3q74l3v0pswpdpa63wlkqmc8q35fkdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVajdBOVNJb3dmYStjUzZV
            ckYrcy9ESTNQbHJDZEQvSFdkVkk2YlN4Ym13CmlabFVYQ3haSTNYTWkwaHQrL2Ji
            UlBSZ1hvV0tCYnVJVTdwN3ZINnlabTQKLS0tIGFsc3ZxMktGRGxHbzlCdDNSS3Zt
            WUY1UFozRnlZWHo0V3RxOWZlRW1Bc28KWZeIJnuZF6TlVBY+PU839QR7uAcRxdoU
            Ee67YiLXUG8SWZUIok6Ksgef5lHb35e+uh7DZcbHXLklpbUF5IoxEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T05:44:53Z"
    mac: ENC[AES256_GCM,data:D5eMODfaO3AzZtlVlNwBo2hGArWoJQOGtiQCqIpXqrRNemh/J5zNoun7ZHrzu5ZgF1SvvjpFuZy/pFbJ7ciFKNe4I9bhAb29qs/6QgXbBcBBIyUqW8dy6s8hT7FSBP+W7HxGcL7YAoa2kbBPTlpo5sTnwPWkDguD0KJZaB+XHrQ=,iv:2EWrXgSG/5dIWXwC7OgldFD5pelZrFPritxhL5f5xh0=,tag:+PcxkyHraNT8vE3YplWGwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
