basic_auth:
    user: ENC[AES256_GCM,data:giriAvE=,iv:GAlAq1oRgNB/3yktPuA3hlNNMmJ+mZ3/5yc71zrPHrs=,tag:omn6YTxORil20WuqojjPNA==,type:str]
    password: ENC[AES256_GCM,data:JivpjEAPUSnB,iv:oKXhD4lL6RGRaJ3MKabKA8Qwf9EWrJPLndePV8JXdIg=,tag:iSoF6KdsIu171SdN07qjXg==,type:str]
    credentials: ENC[AES256_GCM,data:pzY1B2KzUpidLGEkhmS7WwFYJl/CcyUoHfgCfepKO0zuoq+eLTfn+lc6Ww==,iv:kwyBlchTinGw0dOPl5FK7i96f1BsrzIy0f8VRJEPpho=,tag:qtF8ny2SadgCoRqPb/UCzQ==,type:str]
apps:
    testing:
        authelia_test_password: ENC[AES256_GCM,data:dDsZZr/OeTDqqsMf273hsA==,iv:1KMe9jtF6VJb85W2gVijA4nh59+BbjS/8SUyVANN93g=,tag:GI4QbHgr30mZiKLAfDLsiQ==,type:str]
    services:
        core:
            gitea:
                admin_user: ENC[AES256_GCM,data:NOOHLd4=,iv:JCernuR7A+CsLlADz8S3fW3HppbRUWjsKQ+u9Xdu8X8=,tag:5wt6kXa4LKixmtzKh9WNiw==,type:str]
                admin_password: ENC[AES256_GCM,data:yFTG8Un8lhv1,iv:v3h5yGw4LwmHjtIQD7O/gvSjtqsp83dBOptVrDwEFZQ=,tag:88TKAzo3Eb/a5lKOYpSgtA==,type:str]
            n8n:
                encryption_key: ENC[AES256_GCM,data:4m4KfCMjMqyn5ACTrZ6B45ShfnhD50rUN6/s+ULwRhM=,iv:Djs28+0rpBu4JOqII1bjCNdPhCo4m+JFPAwMhzvoIIM=,tag:gjueffRns0o6Wa0iNXuNkg==,type:str]
        data:
            minio:
                root_user: ENC[AES256_GCM,data:nB6AbRU=,iv:r1W5CxMcKTysGmdSFuju58hwFVTuUbZnYEj6AnYDcjc=,tag:Wwp5JcAL0jF7/EXGlnzmKw==,type:str]
                root_password: ENC[AES256_GCM,data:H0bQ0is03P+E,iv:RcbyKeG7+WKbmyu5mbwtGj0KlOLHq2iDg3kLFmEaM8U=,tag:t6q4TbHbSwFOCYPRUiCmTg==,type:str]
                oidc_client_secret: ENC[AES256_GCM,data:rPSXhM2SxvI2MZ6SUPuE911b8xnX/JTqdK4wPtRKa1uPp4NbYF7Lz+qiZmLjonBxJhJZh8yvur3c2IfOnoMbmBkaEop4EuHNPUAlD8tZOh0sei7ZPEE=,iv:+W2oXyiK4Andhhk+i9o+JictaE9hAAfP+u3CvCiYg+0=,tag:XIV5sdFqeJDx2/OgPFmWYg==,type:str]
        observability:
            grafana:
                admin_user: ENC[AES256_GCM,data:3csSO+Q=,iv:3zOMaYJ4Rlsd0mqI56aLVj4AjivhEhQEAUInVpXDJ9E=,tag:QwLAiz+ZThnguaDCu26JHA==,type:str]
                admin_password: ENC[AES256_GCM,data:3BFLP1cfhtfW,iv:Mpx7PUjiNUvawO0IOrCeb25lF5VXVkOb/ftHbOiavDs=,tag:XSGytc2+WiW+HF+V3HMv4w==,type:str]
        security:
            crowdsec:
                bouncer_api_key: ENC[AES256_GCM,data:Lvv+ZhB3eJiGK2VxUMFVqSLqNvyQkFYjcuZ7cgDKjtGbNWKysNRgAYqWlw==,iv:QAFdcwffTsFo0emmwmV7gzMLHeSBZ2M+Pd67ZNyMZv4=,tag:eSLKUTicI5qs5Xyt6O+tOg==,type:str]
            authelia:
                users_admin_password_hash: ENC[AES256_GCM,data:GnUTRg4C7TftZKISQ4CTOimz82lRhBH2psERQM+vs8VKiBPS+25M2CF34MgQUu3jgume6OCVo4qVsEAVCKB0aPRB3Ou4j4MNpM3hN9pqi/AEoWgfyFM1mIOS//C6fPx08w==,iv:Xiq2KVX31FsxrdyjhrZs1wLMogssJBEsi1gFmrbbGHI=,tag:gXT0h29EfheBzlhuAnbqWg==,type:str]
                oidc_hmac_secret: ENC[AES256_GCM,data:7/fFabxat7jGzb+bxjBH//N3Bjv0x5NqD+hmIEdHm0rUJpuYGjM52p6XAA6BfUCgoYExzXah2mtIJboVMkEr4NlCFN1qTL3cSwuQi+GgjHWQOdDwG/o=,iv:9ffxKX6PD4JyVDKjK8UgTfqjB6slNSibzSE0xFN6Yzs=,tag:GxkMkRijUks4kxcBPoPaaw==,type:str]
                session_secret: ENC[AES256_GCM,data:iooG2YpnqD00FltiM9S4Oz89ahwLMcYdz/xtgryrvjvzHymJFCDbTxe+/ZLsjWp/vMvb6B2PuUgo74+9ysLCwh6m4GzboB1Ce0MNARBH3M0Xgib7Szs=,iv:2EDvqEyz5plF9oiOzjYtCL/h/srpGvF8E0pY5dPSTLM=,tag:P7D49cwJFggoyBo29uVFOQ==,type:str]
                storage_encryption_key: ENC[AES256_GCM,data:Sf1O3viSF9/bK2XxKnBFEs1jvIz1Ik9odVu2lJk3+Ye0P58b6UkTAHJtFMoEiJRON3aZg6lKx9bCR+I5y1ANIPS72KPgeEHMVS6+VMo7ipg3PnriMvc=,iv:niIumeLoRAvEg8Axg9lT1uyeW7U9jrdnDZumnV3Yc3Y=,tag:DI41k2ae5Gb3G5HM7XhL+g==,type:str]
                jwt_secret_reset_password: ENC[AES256_GCM,data:bZfnxAPxdCXWa5nhD2B9HmNj5+pJkCgh8+f5fhvJvTpE6XUAbCBFpu9FqtYBo01BM4Y+8ArkWkaj5jLbwYr359ii2yGa7o0tDg76N+O/pi0HzYOInYk=,iv:bwlCSF+GvKgpq+7zknKb/2Zq83BN258XBTTENuTc09U=,tag:sVkPsMiC7ZaIuW5K3lnA/g==,type:str]
                oidc_client_secret: ENC[AES256_GCM,data:3PGs6n1EO2VMcPDle0Uo03CMuq3Wowoqp/4ewXmMq3lTS+owzyV5hO98Avl+lmPlNocDv28tzx2JUpLMkXxssX6RVhAg/oHR+YaO2c5q80h2zdTkPNE=,iv:byYSMxGVx4PVaZMCwBhCmQ0mKL73DWMFNCqs51KXpzI=,tag:A7hhM2p1yJHjHcKGluyBcA==,type:str]
                oidc_client_secret_hash: ENC[AES256_GCM,data:GIWtYwvf14m6L54fsEjTrTp8HgWPD2NGLcS05ZX96Dia9142bfq4mqaTHnWmySUHNZmH6fRcvV9REy+sbWBA4hfu4At3DxrKMGLK46vm7w2+pGtxEkvDeTQwd615cyptPw==,iv:slJnewlxIVOJ/2eCUh2xN8BYY8v6AO0ipyxpPjVWyBE=,tag:q7dbgI5+8RVZMW/Vjvmjyg==,type:str]
                oidc_client_secret_grafana: ENC[AES256_GCM,data:Ph/k/ytp+W7sqXkW8TFiNPmGu6PMhVFg9dEtnHuLtfsfayzXeCofL7lLFHt3p+ydD1iGpeiGR91IMTbqrIhgX2E9FgZMCaFCCA651Cg1SWqC1yrW0Sw=,iv:itEvpoKqhxej0X+BAUjEbrCs81wOtqjwzYF2fqluoY4=,tag:2k90408sGQmr4KFTayH3Tg==,type:str]
                oidc_client_secret_grafana_hash: ENC[AES256_GCM,data:QNlkk1kHT04y286V4G2McLHrM4JAbUfSRR1oaA07t1GanMhtveV/ro/47OwiErVCeq0dIDyiP4FmvOvbnPO4i9WYHzDqtIC/AflqBhn8wZRvAqhjOlw2YQ9ooN88Db1FyA==,iv:QgXC6fqjiKZGTx5WSTuwabtGPfLmL103D9csvofg2Xg=,tag:8ZXNUBznZllRDvUdQ3hcMQ==,type:str]
                oidc_client_secret_minio_hash: ENC[AES256_GCM,data:U3yfUz8ARjTCPPUQA8/OhBPF7dZrvZghyme8qM0I6nU2kthh0+vIVMYIeFuKtEjPkWRn+EEF0nO/6TL2YB6eEM5af5djTBv4hICw2wLpatC+f12RWGg8zvC5eU001wpS+Q==,iv:ySdUjXFboC0DA7GKCwxpKlBnk1We1TEh6lh9cM1jGXI=,tag:7PPEH+dzrOgbpcrD+R9C2g==,type:str]
                users_testuser_password_hash: ENC[AES256_GCM,data:XrjPLxTp3OLSpW+NQnQMuIjXWdx871GgqMpe6yHx+UQ0WVzxButjnEQN0ub3ACu8xUF11v1ObgzwefJsO/cYrhLtyaD044RhFdoihjfz8z/L9Ul4zkkYKRU9wm0rQNMsYw==,iv:mvXTf0KZZcfIGj7v0KAqZbfHEvRcQ25I/f0JZe023Tk=,tag:t4Pm6Q7V/SSMYVRizx54Rg==,type:str]
sops:
    age:
        - recipient: age166v8efpskctmxxes5lcqpxkj0ny3q74l3v0pswpdpa63wlkqmc8q35fkdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK3VpU3dQRGEwVml3UXh2
            NVpwSjRrU3ZGV3RlVEN5UWoxSGlGRi9YN25jCk1mUi9BMWF6NXNYS01lajFFVjJ3
            V1lVckdrelRCL21MNHNlakN5cWhTMG8KLS0tIGxxK1NlWm5LN2hoRU9QK0dENGpz
            TnhWc3Z2cVROSjZidzlaNXZPYy9hWGcKMDXeu0UcetFjPiTVOcoqEWe34+nl2y7m
            Vn/WhrzCLwcdy6lcxjOGQa7XMZmCgSQ9TFWbYICh8gBdA/CMgAIZug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wpqxa7vqkr6watypd6zlw7kspz506kq2kvluxnluhz72mgtaga3qlg84cv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRVBiT1NQUS9BR1hBQ1hz
            eGtJYkt1ejY0dDdvQVZ6RklyazJsL2ZRNjBvCmJDM1A3d2hPVmg4eGhrblpsQ0xU
            NFZyWDdqeUdrTUhPb0RBb2VyYzVieFEKLS0tIG5mTXlUZ3ZiR3RJMzQ5SWhYL2hw
            N21wN3Z0Z2YvdDJPVFpFSkNSWEZPeWcK4x+DaPKz6LlbDTy+vt5buy1aYfBf+mQC
            PB5mUWFYd0vHwxJ9GGsRS/2uZi4T61ZH4AJUO3fDGB0Bsyp4UzE2oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T01:52:40Z"
    mac: ENC[AES256_GCM,data:T2loJqUuec5sjym/z+mCqQUe88+ECglCfJtpOxHZ8U2XUp/NhFqaxj14V+c4oQzPZg5ySKeCl7bSS2iGumZDZAtWad57ydZ5rByoQ6AA79rWhGbwZntvGqyI1giasbIVtyl9YIpyXG1d83BMqOSWlqULEqwvBVb/GP316z3Yr2E=,iv:eKVmCQhH/y0nFl3TQrZGu92Re2PlcaSOe6+Zdoh3jQE=,tag:geFZoDolNR0IMDF3fl47mw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
