#!/bin/bash

# Environment Variables
WIFI_SSID="EcosDeSanJacinto-5G"
WIFI_PASS="pixeleurope@nafocus"
WIFI_BSSID="a8:97:cd:15:ae:3e"

# New Router Architecture
LAN_IP="192.168.2.1"
LAN_NET="192.168.2.0/24"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

echo ">>> STARTING CUBELAB ROUTER CONFIGURATION <<<"

# 1. BACKUPS
echo "[*] Performing security backup..."
[ -f /etc/network/interfaces ] && cp /etc/network/interfaces /etc/network/interfaces.bak.$TIMESTAMP
[ -f /etc/dnsmasq.conf ] && cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak.$TIMESTAMP

# 2. INSTALL DNSMASQ (DHCP Server)
echo "[*] Installing DHCP server..."
# Avoid interactive prompts
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y dnsmasq -qq

# 3. CONFIGURE DHCP
echo "[*] Configuring DHCP for range 192.168.2.50-150..."
cat <<EOF > /etc/dnsmasq.conf
# CubeLab Configuration - Generated by Script
interface=vmbr0
bind-interfaces
# Range for Raspberrys and VMs
dhcp-range=192.168.2.50,192.168.2.150,12h
# Gateway is this Proxmox
dhcp-option=3,$LAN_IP
# DNS Cloudflare and Google
dhcp-option=6,1.1.1.1,8.8.8.8
EOF

# 4. GENERATE INTERFACES (With typo corrections and NAT enabled)
echo "[*] Rewriting /etc/network/interfaces..."
cat <<EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

# --- PHYSICAL PORTS (BRIDGE) ---
auto nic0
iface nic0 inet manual

auto nic1
iface nic1 inet manual

# --- WAN (WIFI) ---
auto wlp2s0
iface wlp2s0 inet dhcp
    wpa-ssid "$WIFI_SSID"
    wpa-psk "$WIFI_PASS"
    wpa-bssid $WIFI_BSSID
    # Optimize WiFi Performance
    post-up /sbin/iw dev wlp2s0 set power_save off
    post-up /sbin/ethtool -K wlp2s0 gso off gro off tso off
    post-up /sbin/ethtool -C wlp2s0 adaptive-rx off rx-usecs 0 tx-usecs 0

# --- LAN (ROUTER) ---
auto vmbr0
iface vmbr0 inet static
    address $LAN_IP/24
    bridge-ports nic0 nic1
    bridge-stp off
    bridge-fd 0

    # Enable NAT for LAN to WAN routing
    post-up echo 1 > /proc/sys/net/ipv4/ip_forward
    post-up iptables -t nat -A POSTROUTING -s '$LAN_NET' -o wlp2s0 -j MASQUERADE
    post-down iptables -t nat -D POSTROUTING -s '$LAN_NET' -o wlp2s0 -j MASQUERADE
EOF

# 5. ENABLE PERMANENT FORWARDING
echo "[*] Enabling IP Forwarding in sysctl..."
sed -i '/net.ipv4.ip_forward/d' /etc/sysctl.conf
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf

echo "----------------------------------------------------"
echo " CONFIGURATION APPLIED (Files generated)"
echo "    ATTENTION: A reboot is required to activate the new Router."
echo "   Your access IP will change from 192.168.2.2 to 192.168.2.1"
echo "   Run 'reboot' when you are ready."
echo "   Then IPs distiribution will be automatic via DHCP and can be checked with:"
echo "     'cat /var/lib/misc/dnsmasq.leases' command"
echo "----------------------------------------------------"
echo ">>> CUBELAB ROUTER CONFIGURATION COMPLETED <<<"
