services:
  wiki:
    image: "${REGISTRY}/${IMAGE_NAME}:latest"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    expose:
      - ${PORT}  
    env_file:
      - ./.env
    networks:
      - proxy      

networks:
  proxy:
    external: true
