"""Sync IDP brand CSS from common.yaml SSOT.

Reads branding design tokens (palette, typography) from infra/config/values/common.yaml
and generates the master brand stylesheet in edge/errors/html/brand/brand.css.

Complies with ADR-027 drift detection contract.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

from toolkit.core.io import write_text_lf

PROJECT_ROOT = Path(__file__).resolve().parents[2]
COMMON_YAML = (PROJECT_ROOT / "infra/config/values/common.yaml").resolve()
OUTPUT_CSS = (PROJECT_ROOT / "edge/errors/html/brand/brand.css").resolve()

DEFAULT_PALETTE: dict[str, str] = {
    "primary": "#0E7490",
    "primary_hover": "#155E75",
    "accent": "#3F51B5",
    "accent_light": "#5C6BC0",
    "bg_dark": "#09090B",
    "surface_dark": "#18181B",
    "surface_hover": "#27272A",
    "border_dark": "rgba(255, 255, 255, 0.08)",
    "text_primary": "#F4F4F5",
    "text_secondary": "#D4D4D8",
    "text_muted": "#A1A1AA",
}

DEFAULT_TYPOGRAPHY: dict[str, str] = {
    "font_sans": "Inter, -apple-system, sans-serif",
    "font_mono": "'JetBrains Mono', monospace",
}


def generate_brand_css(branding: dict[str, Any]) -> str:
    """Render master CSS variables from branding tokens."""
    palette = {**DEFAULT_PALETTE, **branding.get("palette", {})}
    typography = {**DEFAULT_TYPOGRAPHY, **branding.get("typography", {})}

    primary = palette["primary"]
    primary_hover = palette["primary_hover"]
    accent = palette["accent"]
    accent_light = palette["accent_light"]
    bg_dark = palette["bg_dark"]
    surface_dark = palette["surface_dark"]
    surface_hover = palette["surface_hover"]
    border_dark = palette["border_dark"]
    text_primary = palette["text_primary"]
    text_secondary = palette["text_secondary"]
    text_muted = palette["text_muted"]

    font_sans = typography["font_sans"]
    font_mono = typography["font_mono"]

    return f"""/* ==========================================================================
   KubeLab IDP — Master Brand Design System Tokens
   SSOT: infra/config/values/common.yaml (branding)
   Generated by toolkit sync branding. Do NOT edit directly.
   ========================================================================== */

:root {{
  /* Colors — Brand Core */
  --kl-primary: {primary};
  --kl-primary-hover: {primary_hover};
  --kl-accent: {accent};
  --kl-accent-light: {accent_light};

  /* Colors — Dark Surface Theme */
  --kl-bg-dark: {bg_dark};
  --kl-surface-dark: {surface_dark};
  --kl-surface-hover: {surface_hover};
  --kl-border-dark: {border_dark};

  /* Colors — Typography */
  --kl-text-primary: {text_primary};
  --kl-text-secondary: {text_secondary};
  --kl-text-muted: {text_muted};

  /* Typography */
  --kl-font-sans: {font_sans};
  --kl-font-mono: {font_mono};

  /* Layout & Geometry */
  --kl-radius-sm: 0.25rem;
  --kl-radius-md: 0.5rem;
  --kl-radius-lg: 0.75rem;
  --kl-transition: all 0.15s ease-in-out;
}}
"""


def main() -> int:
    """Load branding from common.yaml and write brand.css."""
    if not COMMON_YAML.exists():
        print(f"Error: {COMMON_YAML} not found", file=sys.stderr)
        return 1

    with open(COMMON_YAML, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    branding = data.get("branding", {})
    if not branding:
        print("Error: no 'branding' block found in common.yaml", file=sys.stderr)
        return 1

    css_content = generate_brand_css(branding)
    OUTPUT_CSS.parent.mkdir(parents=True, exist_ok=True)
    write_text_lf(OUTPUT_CSS, css_content)
    try:
        rel_path = OUTPUT_CSS.relative_to(PROJECT_ROOT)
    except ValueError:
        rel_path = OUTPUT_CSS
    print(f"Synced {rel_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
