services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: always
    env_file:
      - ".env"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./certs/acme.json:/letsencrypt/acme.json"
      - "./dynamic:/etc/traefik/dynamic"
      - "./logs:/logs"
    command:
      - "--providers.file.directory=/etc/traefik/dynamic"    
    networks:
      - proxy

networks:
  proxy:
    external: true