services:
  grafana:
    image: grafana/grafana-oss
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env.dev
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - proxy

volumes:
  grafana_data:

networks:
  proxy:
    external: true