services:
  web:
    container_name: ${APPS_PLATFORM_WEB_NAME}
    image: ${REGISTRY}/${APPS_PLATFORM_WEB_IMAGE_NAME}:${APPS_PLATFORM_WEB_VERSION}
    build:
      context: ../../../../apps/web
      dockerfile: Dockerfile
      args:
        PUBLIC_ALLOWED_HOSTS: ${APPS_PLATFORM_WEB_ALLOWED_HOSTS}
        PUBLIC_SITE_TITLE: ${APPS_PLATFORM_WEB_SITE_TITLE}
        PUBLIC_SITE_DESCRIPTION: ${APPS_PLATFORM_WEB_SITE_DESCRIPTION}
        PUBLIC_SITE_DOMAIN: ${APPS_PLATFORM_WEB_SITE_DOMAIN}
        PUBLIC_SITE_URL: ${APPS_PLATFORM_WEB_SITE_URL}
        PUBLIC_SITE_MAIL: ${APPS_PLATFORM_WEB_SITE_MAIL}
        PUBLIC_SITE_AUTHOR: ${APPS_PLATFORM_WEB_SITE_AUTHOR}
        PUBLIC_SITE_KEYWORDS: ${APPS_PLATFORM_WEB_SITE_KEYWORDS}
        PUBLIC_TWITTER_URL: ${APPS_PLATFORM_WEB_TWITTER_URL}
        PUBLIC_YOUTUBE_URL: ${APPS_PLATFORM_WEB_YOUTUBE_URL}
        PUBLIC_GITHUB_URL: ${APPS_PLATFORM_WEB_GITHUB_URL}
        PUBLIC_CALENDLY_URL: ${APPS_PLATFORM_WEB_CALENDLY_URL}
        PUBLIC_BUY_ME_A_COFFEE_URL: ${APPS_PLATFORM_WEB_BUY_ME_A_COFFEE_URL}
        PUBLIC_GOOGLE_ANALYTICS_ID: ${APPS_PLATFORM_WEB_GOOGLE_ANALYTICS_ID}
        PUBLIC_GOOGLE_TAG_MANAGER_ID: ${APPS_PLATFORM_WEB_GOOGLE_TAG_MANAGER_ID}
        PUBLIC_ENABLE_HOMELABS: ${APPS_PLATFORM_WEB_ENABLE_HOMELABS}
        PUBLIC_ENABLE_BLOG: ${APPS_PLATFORM_WEB_ENABLE_BLOG}
        PUBLIC_ENABLE_CONTACT: ${APPS_PLATFORM_WEB_ENABLE_CONTACT}
        BACKEND_URL: ${APPS_PLATFORM_WEB_BACKEND_URL}
    restart: ${RESTART_POLICY}
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl -f http://localhost:${APPS_PLATFORM_WEB_DEFAULT_PORT}${APPS_PLATFORM_WEB_HEALTH_PATH}
          || exit 1
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
