"""Render `infra/terraform/gcp/gcp.tfvars` from `common.yaml`.

WHY THIS IS NOT `aws-tfvars` WITH THE NAMES CHANGED. That command exists to
inject two SOPS values into Terraform and delete the file afterwards. The GCP
module needs neither: cloud-init reads its credentials from Secret Manager at
boot through the instance's service account, so Terraform carries no secret at
all. Measured 2026-08-21: all 19 variables in `variables.tf` have a default and
none is `sensitive`.

The SHAPE survives -- a toolkit command, `-var-file`, removed after use -- and
the CONTENT is redefined to the thing that actually duplicates: the Terraform
defaults restate `common.yaml`, and `TestModuleDefaultsMatchTheSSOT` currently
guards that by comparison because nothing renders it. Its own docstring says so:
"Until `gcp-tfvars` renders these inputs from `common.yaml`".

WHAT IS RENDERED IS DERIVED, NOT LISTED. Every key under `networking.gcp` whose
name equals a Terraform variable is rendered by computation, so a key added to
the SSOT is picked up without anyone remembering a second list. Only the pairs
that cross into another section have no such rule, and those are declared in
`SSOT_PATHS` below -- which is the honest difference between a value absent
because it is computed and one absent because it was forgotten.

The defaults in `variables.tf` deliberately STAY. They are what
`_var_defaults_any` reads, and that is the mechanism of the IAM-grants-match-the-
catalog guard; removing them to eliminate the duplication would disable a
security check to tidy a redundancy. Removing them is a possible follow-up with
that guard reworked first, not a side effect of this change.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from toolkit.features import argocd_spokes

# Variables whose SSOT lives OUTSIDE `networking.gcp`, so no name rule reaches
# them. Terraform variable name -> dotted path in common.yaml.
SSOT_PATHS: dict[str, str] = {
    "argocd_chart_version": "argocd.chart_version",
    "helm_version": "argocd.helm_version",
    "deploy_user": "networking.ssh_users.cloud",
}

# Rendered from a derivation rather than a config key. Kept separate because a
# derived value has no single SSOT path to name, and pretending otherwise is the
# scalar-vs-derivation error ADR-063 D4 exists to catch.
DERIVED = ("spoke_servers",)


def _dig(config: dict[str, Any], dotted: str) -> Any:
    node: Any = config
    walked: list[str] = []
    for part in dotted.split("."):
        if not isinstance(node, dict) or part not in node:
            raise KeyError(f"common.yaml has no {dotted!r} (resolved as far as {'.'.join(walked) or '<root>'})")
        node = node[part]
        walked.append(part)
    return node


def _hcl(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_hcl(v) for v in value) + "]"
    return '"{}"'.format(str(value).replace("\\", "\\\\").replace('"', '\\"'))


def _check(name: str, value: Any) -> Any:
    if value is None or (isinstance(value, str) and not value.strip()):
        raise ValueError(
            f"{name} resolves to an empty value. An empty string is valid HCL, so this "
            f"would plan against a blank input and fail at apply wearing the cloud "
            f"provider's error message instead of this one."
        )
    return value


def resolve(config: dict[str, Any], variable_names: set[str]) -> dict[str, Any]:
    """Every tfvars entry this config yields, restricted to declared variables.

    `variable_names` is what the module actually declares. Rendering a value for
    a variable Terraform does not declare fails the plan with "undeclared
    variable", so the intersection is taken here rather than discovered there.
    """
    out: dict[str, Any] = {}

    gcp = config.get("networking", {}).get("gcp", {})
    for key, value in gcp.items():
        if key in variable_names:
            out[key] = _check(key, value)

    for var_name, dotted in SSOT_PATHS.items():
        if var_name in variable_names:
            out[var_name] = _check(var_name, _dig(config, dotted))

    if "spoke_servers" in variable_names:
        out["spoke_servers"] = argocd_spokes.apiserver_urls(config)

    return out


def render(config: dict[str, Any], variable_names: set[str]) -> str:
    """The tfvars file body."""
    lines = [
        "# GENERATED by `toolkit infra terraform gcp-tfvars` -- do not edit.",
        "# Source of truth: infra/config/values/common.yaml. Carries NO secret:",
        "# the hub reads its credentials from Secret Manager at boot (ADR-063 D7).",
        "",
    ]
    entries = sorted(resolve(config, variable_names).items())

    # Align the `=` the way `terraform fmt` does, which is not "pad everything":
    # scalars align within a CONTIGUOUS RUN, and a multi-line block assignment is
    # left unpadded AND ends the run. Measured against `terraform fmt` rather
    # than assumed -- padding the block line was the first attempt and fmt
    # rewrote it straight back.
    #
    # This matters because the file is generated: one that `fmt -check` rewrites
    # turns any repo-wide format gate into a race with whichever target last
    # rendered it.
    scalars = [(n, v) for n, v in entries if not isinstance(v, dict)]
    width = max((len(n) for n, _ in scalars), default=0)
    for name, value in entries:
        if isinstance(value, dict):
            lines.append(f"{name} = {{")
            inner = max((len(k) for k in value), default=0)
            lines.extend(f"  {k.ljust(inner)} = {_hcl(v)}" for k, v in sorted(value.items()))
            lines.append("}")
        else:
            lines.append(f"{name.ljust(width)} = {_hcl(value)}")
    return "\n".join(lines) + "\n"


def declared_variables(variables_tf: str) -> set[str]:
    """Variable names the module declares, read from its own source."""
    import re

    return set(re.findall(r'^variable\s+"([a-z_0-9]+)"', variables_tf, re.M))


def write(config: dict[str, Any], gcp_dir: Path) -> Path:
    """Render and write `gcp.tfvars` next to the module."""
    variable_names = declared_variables((gcp_dir / "variables.tf").read_text())
    path = gcp_dir / "gcp.tfvars"
    path.write_text(render(config, variable_names))
    return path
