"""Render the R2 Terraform root's inputs from `backup.*` in common.yaml (BACKUP-057).

Plaintext only, like `vps-firewall-tfvars`: bucket names, the lock's prefixes and
its age are policy and belong in a reviewable diff. The Cloudflare token travels
separately, as `TF_VAR_cloudflare_api_token` in the child process's environment.
"""

from __future__ import annotations

from typing import Any

NODE_BUCKET_PREFIX = "kubelab-backup-"

# The Terraform root's scratch bucket. Declared there with no `prevent_destroy`,
# so no node may be rendered onto the same name.
SCRATCH_BUCKET = f"{NODE_BUCKET_PREFIX}scratch"

# The parts of a restic repository that are written once and never rewritten.
# `locks/` is deleted by every `backup`, and `index/` is rewritten by every
# `prune`; locking either fails the nightly ship. The index can be rebuilt from
# the packs (`restic repair index`), so leaving it out costs availability, never
# data. `config` is a single object, not a directory, hence no slash.
LOCKED_PREFIXES = ("data/", "snapshots/", "keys/", "config")

SECONDS_PER_DAY = 86400


class RenderError(ValueError):
    """The SSOT cannot be rendered; the message names the key to fix."""


def node_bucket(node: str) -> str:
    return f"{NODE_BUCKET_PREFIX}{node}"


def render(config: dict[str, Any]) -> str:
    backup = config.get("backup") or {}
    r2 = backup.get("r2") or {}
    sources = backup.get("sources") or {}

    if not sources:
        raise RenderError("backup.sources is empty or absent in common.yaml: there is no node to give a bucket.")
    for key in ("account_id", "lock_retention_days"):
        if not r2.get(key):
            raise RenderError(f"backup.r2.{key} is empty or absent in common.yaml. Refusing to render.")

    buckets = {node: node_bucket(node) for node in sorted(sources)}
    clash = [node for node, bucket in buckets.items() if bucket == SCRATCH_BUCKET]
    if clash:
        raise RenderError(
            f"backup.sources node {clash[0]!r} would be stored in {SCRATCH_BUCKET}, the scratch "
            "bucket, which a plan is allowed to destroy. Rename the node."
        )

    days = r2["lock_retention_days"]
    if isinstance(days, bool) or not isinstance(days, int) or days <= 0:
        raise RenderError(
            f"backup.r2.lock_retention_days must be a positive whole number of days, got {days!r}. Refusing to render."
        )
    # Keys are quoted: an HCL identifier cannot start with a digit.
    keys = {node: f'"{node}"' for node in buckets}
    width = max(len(key) for key in keys.values())
    prefixes = ", ".join(f'"{p}"' for p in LOCKED_PREFIXES)

    lines = [
        "# GENERATED by `toolkit infra terraform r2-tfvars` -- do not edit.",
        "# SSOT: backup.{r2,sources} in infra/config/values/common.yaml",
        f'account_id           = "{r2["account_id"]}"',
        f"lock_max_age_seconds = {days * SECONDS_PER_DAY}",
        f"locked_prefixes      = [{prefixes}]",
        "node_buckets = {",
        *(f'  {keys[node].ljust(width)} = "{bucket}"' for node, bucket in buckets.items()),
        "}",
    ]
    return "\n".join(lines) + "\n"
