---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api
  namespace: kubelab
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: kubelab
    app.kubernetes.io/managed-by: toolkit
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.kubelab.live`)
      kind: Rule
      middlewares:
        - name: error-pages
      services:
        - name: api
          port: 8080
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: kubelab
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: kubelab
    app.kubernetes.io/managed-by: toolkit
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mlorente.dev`)
      kind: Rule
      middlewares:
        - name: error-pages
      services:
        - name: web
          port: 4321
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blog
  namespace: kubelab
  labels:
    app.kubernetes.io/name: blog
    app.kubernetes.io/part-of: kubelab
    app.kubernetes.io/managed-by: toolkit
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`blog.kubelab.live`)
      kind: Rule
      middlewares:
        - name: error-pages
      services:
        - name: blog
          port: 4000
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catch-all
  namespace: kubelab
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/component: edge
    app.kubernetes.io/part-of: kubelab
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`.+\.kubelab\.live`)
      kind: Rule
      priority: 1
      services:
        - name: nginx-errors
          port: 80
  tls:
    certResolver: letsencrypt
