# ansible/inventory/hosts.yml
---
all:
  hosts:
    vps_ml:
      ansible_host: {{ ANSIBLE_HOST }}
      ansible_user: {{ ANSIBLE_SSH_USER }}
      ansible_port: {{ ANSIBLE_HOST_PORT }}
      ansible_python_interpreter: /usr/bin/python3