services:
  loki:
    deploy:
      resources:
        limits:
          cpus: "${APPS_SERVICES_OBSERVABILITY_LOKI_RESOURCES_CPU_LIMIT}"
          memory: "${APPS_SERVICES_OBSERVABILITY_LOKI_RESOURCES_MEMORY_LIMIT}"
        reservations:
          cpus: "${APPS_SERVICES_OBSERVABILITY_LOKI_RESOURCES_CPU_RESERVATION}"
          memory: "${APPS_SERVICES_OBSERVABILITY_LOKI_RESOURCES_MEMORY_RESERVATION}"

  vector:
    deploy:
      resources:
        limits:
          cpus: "${RESOURCES_DEFAULT_CPU_LIMIT}"
          memory: "128M"
        reservations:
          cpus: "${RESOURCES_DEFAULT_CPU_RESERVATION}"
          memory: "64M"
