services:
  api:
    image: "${REGISTRY}/${IMAGE_NAME}:${TAG}"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    expose:
      - ${PORT}  
    env_file:
      - ./.env.dev
    volumes:
      - ./src:/app/src:cached
      - .env.dev:/app/.env
    command: ["air", "-c", ".air.toml"]
    networks:
      - proxy

networks:
  proxy:
    external: true
