name: Deploy (staging & production)

on:
  push:
    branches: [develop, master]
  workflow_dispatch:
    inputs:
      environment:
        description: 'staging o production'
        required: true
        default: 'staging'
      tag:
        description: 'Imagen a desplegar (latest | develop | v1.2.3 | SHA)'
        required: true
        default: 'latest'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch'
                       && inputs.environment
                       || (github.ref == 'refs/heads/master' && 'production' || 'staging') }}
      tag:         ${{ github.event_name == 'workflow_dispatch'
                       && inputs.tag
                       || 'latest' }}
    secrets: inherit
